### PR TITLE
Wappalyzer Update 2020-12-03

### PR DESCRIPTION
**Pull request by zapbot**
Updates based on AliasIO/Wappalyzer@f6d9c17

Signed-off-by: zapbot <12745184+zapbot@users.noreply.github.com>

### CODE REVIEW

**Comment by thc202** [comment]
How far are you? About to finish the cleanup...

**Comment by kingthorin** [comment]
Haven't started, go ahead. Thank you!

**Comment by thc202** [comment]
Pushed.

**Comment by thc202** [comment]
Upstream file will have to be cleaned up, has duplicated entries again.

**Comment by kingthorin** [comment]
Okay, I can look at opening a PR for them.

**Comment by thc202** [comment]
Thanks!

**Review by kingthorin — APPROVED** [review]

**Review by thc202 — APPROVED** [review]

**Comment by kingthorin** [comment]
Looks like upstream was corrected just after our job ran: https://github.com/AliasIO/wappalyzer/commit/c15450533ec962c252ed086856dc15237187f56e#diff-ad6b5aefcc8c0ba3d7c9f4c9ba096652f7bae1235363a40bba4759f3abb374c4

**Pull request merged**
