### PR TITLE
graphql: Fix Issue 6316

### PR DESCRIPTION
**Pull request by ricekot**
- Add two new options
    - Lenient Maximum Query Depth
    - Additional Query Depth
- Fixes zaproxy/zaproxy#6316

Signed-off-by: ricekot <ricekot@gmail.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
Sorry I lost track of this one, will try to review today.

**Review by kingthorin — COMMENTED** [review]
Would it be worth adding a test (or tests) where the input exceeds the lenient attempt? (Ex: The failure branch(es), where an invalid query is still generated) [Hopefully I didn't overlook it.]

Otherwise things look good to me.

**Comment by ricekot** [comment]
Updated with suggested unit test ([lenientDepthExceeded](https://github.com/zaproxy/zap-extensions/pull/2699/files#diff-22f3cd5dc96b7867d4601a63d69690e5f47183cffcd0868dd6b13f40c5eabd6aR340)).

**Review by kingthorin — APPROVED** [review]
Thanks! Looks good to me.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
