### PR TITLE
Issue 2001 commandinjection add powershell variants

### PR DESCRIPTION
**Pull request by kingthorin**
Fixes zaproxy/zaproxy#2001

I haven't updated ZapAddOn.xml in this PR as there's another pending PR for the same package...not sure how we plan to handle such occurrences.

### CODE REVIEW

**Comment by thc202** [comment]
Changes look good, could you add the changes to ZapAddOn.xml?
You need to rebase first though, the other PR was already merged.

I think the changes in ZapAddOn.xml should be added even there are other PRs. Conflicts will happen anyway (to resolve them we can manually merge or ask for a rebase).

**Comment by kingthorin** [comment]
Ok, will do.

Just so I'm clear on workflow. 
In this case:
The other change has been accepted (merged), so I can switch to this branch, fetch (from master), then rebase. Update ZapAddOn.xml and do a fixup push?
In general:
Edit ZapAddOn.xml as I normally would, commit & push, conflicts can be merged at PR accept (or rebase requested per above workflow).

**Comment by thc202** [comment]
Yeah, that's it.

**Comment by kingthorin** [comment]
For some reason within https://github.com/zaproxy/zap-extensions/releases I don't see a 22, but if I google search `ascanrules-release-22.zap` I do see hits against bdd-security and arch linux.... so ZapAddOn.xml was updated with 23. I can do another fixup if I decided wrong (which means I must have had it wrong in the other PR :disappointed:)...just let me know.

**Comment by thc202** [comment]
Yes, version 22 was not released to marketplace but was included in the main ZAP release (without changes).
Bump to 23 is better, to avoid any confusions with the one bundled in ZAP.

**Comment by kingthorin** [comment]
Done

**Comment by thc202** [comment]
Thank you.

**Pull request merged**
