### PR TITLE
graphql: Use Log4j 2.x

### PR DESCRIPTION
**Pull request by kingthorin**
- Update CHANGELOG, and change code to use updated logging infrastructure.
- GraphQlApi > Removed un-used logger instantiation.

Part of: zaproxy/zaproxy#6376

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Review by ricekot — CHANGES_REQUESTED** [review]
Looks good except the GraphQlApi class can also be updated.

**Comment by kingthorin** [comment]
Tweaked 😀

**Review by ricekot — APPROVED** [review]
Thanks!

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
