### PR TITLE
sqliplugin: update ZAP to 2.10.0

### PR DESCRIPTION
**Pull request by thc202**
Update ZAP to 2.10.0.
Use Log4j 2 APIs.

Part of zaproxy/zaproxy#6376.

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]

**Review by psiinon — APPROVED** [review]

**Comment by ricekot** [comment]
The if condition at https://github.com/zaproxy/zap-extensions/blob/1f7bec8ed4ad0e224f4fd85f79474035bcdc6230/addOns/sqliplugin/src/main/java/org/zaproxy/zap/extension/sqliplugin/SQLInjectionScanRule.java#L422 can be removed.

**Comment by thc202** [comment]
Removed some level checks no longer needed, pointed out in irc, thanks @ricekot :)

**Comment by thc202** [comment]
Further tweaks, removed string concatenations and a level check.

**Review by ricekot — APPROVED** [review]
Thank you!

**Pull request merged**
