### PR TITLE
Updated for 2.7.0

### PR DESCRIPTION
**Pull request by psiinon**

### CODE REVIEW

**Comment by psiinon** [comment]
Has someone taken the 'p'? :P 
Have added it ;)

**Comment by thc202** [comment]
@psiinon worth waiting for more feedback/reviews before merging?

**Comment by psiinon** [comment]
@thc202 I think its better to merge now - can issue new PRs as and when we get more feedback that we think should be addressed.

**Comment by thc202** [comment]
Done :)

**Comment by psiinon** [comment]
thanks :)

**Pull request merged**
