### PR TITLE
Fix build errors

### PR DESCRIPTION
**Pull request by robocoder**
Eclipse IDE for Java Developers
Version: Luna Service Release 2 (4.4.2)
Build id: 20150219-0600

java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

### CODE REVIEW

**Comment by thc202** [comment]
Builds fine here with same version, which errors are you seeing?

**Comment by robocoder** [comment]
```
Description	Resource	Path	Location	Type
The method showModifyDialogueHelper(T4) in the type MessageLocationPayloadsPanel.PayloadsTablePanel is not applicable for the arguments (PayloadGeneratorUI<capture#10-of ?,capture#11-of ? extends Payload<?>,capture#12-of ? extends PayloadGenerator<?,? extends Payload<?>>>)	MessageLocationPayloadsPanel.java	/zap-extensions_beta/src/org/zaproxy/zap/extension/fuzz/impl	line 233	Java Problem
The method showModifyDialogueImpl(T2) in the type ProcessorsMessageLocationDialog.ProcessorsTablePanel is not applicable for the arguments (PayloadProcessorUI<capture#10-of ?,capture#11-of ? extends Payload<?>,capture#12-of ? extends PayloadProcessor<?,? extends Payload<?>>>)	ProcessorsMessageLocationDialog.java	/zap-extensions_beta/src/org/zaproxy/zap/extension/fuzz/impl	line 203	Java Problem
The method showModifyDialogueImpl(T2) in the type ProcessorsPayloadDialog.ProcessorsTablePanel is not applicable for the arguments (PayloadProcessorUI<capture#10-of ?,capture#11-of ? extends Payload<?>,capture#12-of ? extends PayloadProcessor<?,? extends Payload<?>>>)	ProcessorsPayloadDialog.java	/zap-extensions_beta/src/org/zaproxy/zap/extension/fuzz/impl	line 178	Java Problem
The method wrapProcessedPayloadGenerator(PayloadGenerator<T1,T2>, List<PayloadProcessorTableEntry>) in the type FuzzMessageLocationsPanel is not applicable for the arguments (PayloadGenerator<capture#14-of ?,capture#15-of ? extends Payload<?>>, List<PayloadProcessorTableEntry>)	FuzzMessageLocationsPanel.java	/zap-extensions_beta/src/org/zaproxy/zap/extension/fuzz/impl	line 198	Java Problem
```

**Comment by thc202** [comment]
Thanks!
Do you see the same with Ant build?

**Comment by robocoder** [comment]
No. It looks like it's unique to the Eclipse Java Builder.

**Comment by thc202** [comment]
Thanks. Could you update the commit message to mention that?

**Comment by robocoder** [comment]
Done.

**Comment by thc202** [comment]
Thank you.

**Pull request merged**
