### PR TITLE
chore: Upgrade Log4j to 2.17.2

### PR DESCRIPTION
**Pull request by kingthorin**
Added maintenance note to changelogs where applicable, updated build files.

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by ricekot** [comment]
The changelog of the reports add-on wasn't updated.

**Comment by kingthorin** [comment]
It already contains a note about dependency updates.

**Comment by kingthorin** [comment]
On it.

**Comment by kingthorin** [comment]
Done

**Review by ricekot — APPROVED** [review]
Thanks.

**Review by psiinon — APPROVED** [review]

**Comment by kingthorin** [comment]
Something whack-a-doodle is going on with GitHub, tried merging on both desktop and phone and it says "Merging...." but then pops back to green.

**Pull request merged**
