### PR TITLE
Prevent RFI FP when original title includes 'Google'

### PR DESCRIPTION
**Pull request by psiinon**
Fixes zaproxy/zaproxy#2240

### CODE REVIEW

**Comment by thc202** [comment]
Looks good to me.

**Comment by kingthorin** [comment]
This mod looks fine but I think there's a pre-existing logic issue in the scanner. `REMOTE_FILE_TARGETS` contains 5 entries, `REMOTE_FILE_PATTERNS` contains 6 entries. The loop uses `REMOTE_FILE_TARGETS.length` and both arrays are referenced with index `i` which means the 6th pattern is never reached ... which may also mean that the patterns are misaligned vs the intended target.

**Comment by thc202** [comment]
Indeed, one of the `<title>Google</title>` patterns needs to be removed.

**Comment by psiinon** [comment]
Good spot, will fix that..

**Pull request merged**
