### PR TITLE
sse: increase URL column size

### PR DESCRIPTION
**Pull request by stasha**
Fix zaproxy/zaproxy#7354.

### CODE REVIEW

**Comment by thc202** [comment]
The changelog needs to be updated.
The commit should be signed-off.

**Comment by kingthorin** [comment]
Agreed.

**Comment by thc202** [comment]
Updated the changelog.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Review by psiinon — APPROVED** [review]

**Pull request merged**
