### PR TITLE
 ascanrulesBeta: added non-html check for relative path confusion rule

### PR DESCRIPTION
**Pull request by aryangupta701**

### CODE REVIEW

**Comment by kingthorin** [comment]
Please STOP opening new PRs. If you need advice/guidance on git let us know.

**Comment by thc202** [comment]
They are different scan rules.

**Comment by aryangupta701** [comment]
acutally these PRs are now from astra repo earlier these were from my forked repo.

**Comment by thc202** [comment]
Better not create from org repos as that prevents maintainers from pushing to the PRs.

**Comment by aryangupta701** [comment]
closing this due to access issues

**Comment by kingthorin** [comment]
Do you plan to re-create with a different source?

**Comment by aryangupta701** [comment]
Yes I do plan. Will open them soon.

**Pull request closed without merging**
