### PR TITLE
pscanrules: update reference from http to https

### PR DESCRIPTION
**Pull request by PariharAditya**
## Overview
**fixed from HTTP to HTTPS**
https://www.zaproxy.org/docs/alerts/10050/

## Related Issues
https://github.com/zaproxy/zaproxy/issues/8262

## Checklist
- [ ] Update help
- [ ] Update changelog
- [ ] Run `./gradlew spotlessApply` for code formatting
- [ ] Write tests
- [ ] Check code coverage
- [x] Sign-off commits
- [x] Squash commits
- [x] Use a descriptive title

For more details, please refer to the [developer rules and guidelines](https://www.zaproxy.org/docs/developer/dev-rules-and-guidelines/).

### CODE REVIEW

**Comment by kingthorin** [comment]
To address the DCO requirement you'll need to sign-off the commit(s):

- https://github.com/zaproxy/zaproxy/blob/main/CONTRIBUTING.md#developer-certificate-of-origin
- https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff

**Comment by kingthorin** [comment]
Changes don't seem limited to 10050 and likely clash with other PRs.

**Comment by PariharAditya** [comment]
> Changes don't seem limited to 10050 and likely clash with other PRs.

done all changes for Http to Https in pscanrule Messages.properties

**Comment by thc202** [comment]
The changelog should also be updated.

**Pull request closed without merging**
