### PR TITLE
commonlib: add solution to 'Server Misconfiguration' and 'Application Misconfiguration'

### PR DESCRIPTION
**Pull request by aboyadzhiev**
## Overview
- Add mitigation information about 'Server Misconfiguration' vulnerability.
- Add mitigation information about 'Application Misconfiguration' vulnerability.
- Update changelog.

## Related Issues
https://github.com/zaproxy/zaproxy/issues/8056

### CODE REVIEW

**Comment by kingthorin** [comment]
Are other lists in the file using semi-colon or period?

To me these are full and separate points/actions.

**Comment by aboyadzhiev** [comment]
> Are other lists in the file using semi-colon or period?

My bad will update it in a minute.

> To me these are full and separate points/actions

Not sure I understand you. Do you mean to mark them with 1-n instead of *

**Comment by kingthorin** [comment]
No no, it was just further commentary supporting/suggesting the use of periods.

**Review by thc202 — APPROVED** [review]

**Review by kingthorin — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
