### PR TITLE
Requester: Option to manipulate Host header

### PR DESCRIPTION
**Pull request by psiinon**
## Overview
Adds a button to the requester dialogs for updating the host header.
If disabled then the host header can be manipulated by the user 😁 

## Related Issues

https://github.com/zaproxy/zaproxy/issues/1318

## Checklist
- [x] Update help
- [x] Update changelog
- [x] Run `./gradlew spotlessApply` for code formatting
- [ ] Write tests
- [ ] Check code coverage
- [ ] Sign-off commits
- [x] Squash commits
- [x] Use a descriptive title

For more details, please refer to the [developer rules and guidelines](https://www.zaproxy.org/docs/developer/dev-rules-and-guidelines/).

### CODE REVIEW

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Comment by kingthorin** [comment]
Should the build file be updated to require core >=2.14.0 ?

**Comment by psiinon** [comment]
Nope, this doesnt depend on any core changes - the other PR is independant.

**Comment by kingthorin** [comment]
No I know but I thought on the call you suggested we were going to hold on releasing this till 2.14

**Comment by psiinon** [comment]
Oh right, see what you mean.
I was thinking we would just not release it 😁

**Comment by kingthorin** [comment]
Okay that's fine too.

**Review by kingthorin — APPROVED** [review]

**Pull request merged**
