### PR TITLE
commonlib: add solution for HTTP Response Smuggling vulnerability

### PR DESCRIPTION
**Pull request by jackdvd**
## Overview
Adds possible solutions to prevent the HTTP Response Smuggling vulnerability.

Part of zaproxy/zaproxy#8056.

### CODE REVIEW

**Comment by jackdvd** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by thc202** [comment]
The changelog should be updated.

**Review by kingthorin — COMMENTED** [review]
Text seems fine to me. Just needs a changelog note added.

**Comment by jackdvd** [comment]
I have now updated the change log. Please review.

**Review by kingthorin — APPROVED** [review]

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
