### PR TITLE
ascanrulesBeta: Add newer UA strings to UA fuzz scan rule

### PR DESCRIPTION
**Pull request by kingthorin**
- CHANGELOG > Add, added note.
- UserAgentScanRule > Added new UA constants with comments.

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
Re-ordered the UA constant declarations to group things a bit more.

**Comment by thc202** [comment]
Thank you!

**Review by ricekot — COMMENTED** [review]
It can also include the user agent for the latest internet explorer version (11.0.220) which was discontinued on June 15, 2022.

**Comment by kingthorin** [comment]
Yup I'll add that. Thanks, good call!

**Comment by kingthorin** [comment]
According to: https://www.whatismybrowser.com/guides/the-latest-user-agent/internet-explorer it's `Mozilla/5.0 (Windows NT 10.0; Trident/7.0; rv:11.0) like Gecko`.

**Comment by kingthorin** [comment]
Done

**Review by thc202 — APPROVED** [review]

**Review by ricekot — APPROVED** [review]
Thank you!

**Pull request merged**
