### PR TITLE
spiderAjax: allow choose context/user and set URL

### PR DESCRIPTION
**Pull request by thc202**
Change AJAX Spider dialogue to allow to specify the context and the user
and manually set the start URL.
Change the AJAX Spider API to allow to specify the context and the user
(it was already possible to specify the start URL).
Update changes in ZapAddOn.xml file.
Fork Crawljax's Crawler class (tag 3.6) to allow to spider all URLs
(e.g. a context with multiple hosts included).

Fix zaproxy/zaproxy#1955 - Allow to AJAX spider a context
Fix zaproxy/zaproxy#1956 - Allow to AJAX spider as a user
Fix zaproxy/zaproxy#1957 - Allow URL to be pasted into AJAX Spider
dialogue

### CODE REVIEW

**Comment by psiinon** [comment]
I'm nervous about forking 3rd party classes.
Have you tried sending a PR to the Crawljax project, if so have they responded?
If forking is the only option how well are the changes documented? I'm worried they will be lost if we update to a newer version of Crawljax.

**Comment by thc202** [comment]
I didn't try, (public?) development of Crawljax is pretty stale (last commit/merge was 8 months ago).
The changes have the usual ZAP comment (I can improve that if it's not enough).

**Comment by psiinon** [comment]
@thc202 did you raise a Crawljax issue? I agree its unlikely to be acted upon, but at least it shows we tried ;)

**Comment by thc202** [comment]
Not yet, will check if there's one raised already.

**Comment by thc202** [comment]
The closest issue I could find was crawljax/crawljax#93, the issue would allow to crawl other sites (based on the comments posted in the pull requests to fix the issue).
Worth adding a comment or raise a new one?

**Comment by psiinon** [comment]
Either is fine by me :)

**Comment by thc202** [comment]
Comment added to the mentioned issue.

Is there any change that I need to do to the pull request (other than rebase)?

**Comment by thc202** [comment]
Conflicts resolved.

**Comment by psiinon** [comment]
Looks good

**Pull request merged**
