### PR TITLE
chore: pscanrules: remove use of setParent

### PR DESCRIPTION
**Pull request by kingthorin**
In follow-up to: https://github.com/zaproxy/zaproxy/pull/6598

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by thc202** [comment]
Are these all passive rules or just being done to the main add-on?

**Comment by kingthorin** [comment]
Was doing it as 3 PRs.

**Comment by thc202** [comment]
OK, I'd suggest using the whole add-on ID to be more clear. There are actually 10 add-ons that need to be changed.

**Comment by kingthorin** [comment]
Okay, I'll tweak those. I was also only thinking passive scan for now. But I'll look at tackling them all :wink:

**Comment by thc202** [comment]
OK, thank you.

**Review by psiinon — APPROVED** [review]

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
