### PR TITLE
Pscanrules: performance improvements

### PR DESCRIPTION
**Pull request by psiinon**
## Overview
As per title. Makes a significant difference for all of the changed rules after spidering Juice Shop.

## Checklist
- [x] Update help
- [x] Update changelog
- [x] Run `./gradlew spotlessApply` for code formatting
- [x] Write tests
- [x] Check code coverage
- [x] Sign-off commits
- [x] Squash commits
- [x] Use a descriptive title

For more details, please refer to the [developer rules and guidelines](https://www.zaproxy.org/docs/developer/dev-rules-and-guidelines/).

### CODE REVIEW

**Comment by psiinon** [comment]
WIP as I plan to add a load more, but PRed for initial review, as I plan to change the other rules in the same way.

**Comment by psiinon** [comment]
OK, ready to review.
There are still rules in this add-on like "Suspitios Comments" which are taking a long time, but so far I havnt been able to reproduce the timing problems enough for me to feel confident that anything I do will fix them.
So more investigations will be needed..

**Comment by kingthorin** [comment]
We should be able to improve suspicious comments handling once ANTLR is sorted. (Hopefully)

**Review by kingthorin — APPROVED** [review]

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
