### PR TITLE
bugtracker: address warnings

### PR DESCRIPTION
**Pull request by thc202**
Address remaining warnings and remove compiler flags that were suppressing them.

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]
Thanks!

**Comment by kingthorin** [comment]
Was there an “easy” way to figure out the missing annotation libs?

**Comment by thc202** [comment]
I recall them from zap-admin: https://github.com/zaproxy/zap-admin/blob/1c53097f77bcababf90771e6f42948b32fd5a69e/build.gradle.kts#L55-L58 (I think back when they were added it was a quick search for those annotations).

**Comment by kingthorin** [comment]
Okay, thanks 😀

**Review by ricekot — APPROVED** [review]
Thanks!

**Comment by ricekot** [comment]
Changelog could be updated.

**Comment by thc202** [comment]
Done.

**Review by psiinon — APPROVED** [review]

**Review by kingthorin — APPROVED** [review]

**Pull request merged**
