### PR TITLE
fuzz: update ZAP to 2.10.0

### PR DESCRIPTION
**Pull request by thc202**
Update ZAP to 2.10.0.
Use Log4j 2 APIs.

Part of zaproxy/zaproxy#6376.

### CODE REVIEW

**Comment by kingthorin** [comment]
Thanks for tackling this. There seem to be a number of classes where a logger is declared and unused, should it just be removed?

**Comment by thc202** [comment]
Which one specifically? They should be being used (but might not require any log statement update).

**Comment by kingthorin** [comment]
That's probably what it is, HttpFuzzerTaskProcessorUtils.java for example. I didn't expand the content to see if it was used.

**Review by kingthorin — APPROVED** [review]
Thanks!

**Review by psiinon — APPROVED** [review]

**Pull request merged**
