### PR TITLE
feat: pscanrules all (3): Add WSTG v4.2 alert mappings

### PR DESCRIPTION
**Pull request by kingthorin**
- Added alert mappings to scan rules.
- Updated UnitTests.
- Added change note.

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
Can someone try the Pii unit tests and let me know if they fail locally? Mine seem to but I'm wondering if it's a weird Windows specific thing.

**Comment by thc202** [comment]
Working fine in the command line and failing in Eclipse (JAR hell, picking older version of CSV lib).

**Comment by kingthorin** [comment]
Okay, thanks!

**Review by psiinon — APPROVED** [review]

**Comment by psiinon** [comment]
I must admit I havnt double checked there are any missing categories, but the ones there look good :)

**Comment by kingthorin** [comment]
I'm happy with that. I believe users and others will let us know of misses (if any) over time :wink:

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
