### PR TITLE
Automation: Fix NPE when adding a context to an existing plan

### PR DESCRIPTION
**Pull request by psiinon**
To reproduce:

1. Run the ZAP Desktop
2. Create a new AF plan using the default context
3. Add a new context

An NPE will be logged and the context not added.

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Comment by thc202** [comment]
Add a test (at least in TechnologyUtilsUnitTest)?

**Comment by psiinon** [comment]
Doh, yeah. I was thinking this was just a UI change 😉

**Comment by psiinon** [comment]
Unit tests added.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Review by kingthorin — APPROVED** [review]

**Pull request merged**
