### PR TITLE
Link to the website for dev docs

### PR DESCRIPTION
**Pull request by ArkaprabhaChakraborty**
fixes zaproxy/zaproxy-website#646
Signed-off-by: ArkaprabhaChakraborty <chakrabortyarkaprabha998@gmail.com>

### CODE REVIEW

**Review by kingthorin — COMMENTED** [review]
This doesn't seem quite right. Did you test this? Doesn't it still need the task name after the memory argument?

**Comment by thc202** [comment]
It does, but better link to the website.

**Comment by ArkaprabhaChakraborty** [comment]
uhh I mean ```./gradle build``` is failing for me :)

**Comment by kingthorin** [comment]
I meant `./gradlew -Dorg.gradle.jvmargs=-Xmx2g build`. However as @thc202 said probably better to just link to the dev docs on zaproxy.org

**Comment by ArkaprabhaChakraborty** [comment]
> I meant `./gradlew -Dorg.gradle.jvmargs=-Xmx2g build`. However as @thc202 said probably better to just link to the dev docs on zaproxy.org

ahh yes I missed ```build```

**Comment by ArkaprabhaChakraborty** [comment]
This should be serving the purpose now.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

Worth squash on merge, previous changes are not relevant.

**Review by kingthorin — APPROVED** [review]

**Pull request merged**
