### PR TITLE
kotlin: Add encode-decode template

### PR DESCRIPTION
**Pull request by kingthorin**
## Overview
- CHANGELOG > Added entry.
- encode-decode-template.kts > The new template.

## Related Issues
zaproxy/zaproxy#5996

## Checklist
- [NA] Update help
- [x] Update changelog
- [x] Run `./gradlew spotlessApply` for code formatting
- [NA] Write tests
- [NA] Check code coverage
- [x] Sign-off commits
- [x] Squash commits
- [x] Use a descriptive title

### CODE REVIEW

**Comment by kingthorin** [comment]
I guess this is failing because the tests don't have the Encoder add-on to import from? 🤷‍♂️

Locally:

```bash
$ ./gradlew :addOns:kotlin:test
Starting a Gradle Daemon, 3 incompatible Daemons could not be reused, use --status for details

> Task :buildSrc:jar
:jar: No valid plugin descriptors were found in META-INF/gradle-plugins

> Configure project :addOns:browserView
Project :addOns:browserView => no module-info.java found

> Task :addOns:kotlin:test

ClassLoaderTests > shouldLoadClassesFromProvidedClassLoader() FAILED
    java.nio.file.InvalidPathException at ClassLoaderTests.java:42

VerifyScriptTemplates > shouldParseTemplates() FAILED
    javax.script.ScriptException at VerifyScriptTemplates.java:51

3 tests completed, 2 failed

> Task :addOns:kotlin:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':addOns:kotlin:test'.
> There were failing tests. See the report at: file:///C:/Users/thorin/Desktop/zap-ws/zap-extensions/addOns/kotlin/build/reports/tests/test/index.html

* Try:
> Run with --scan to get full insights.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.2.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 55s
22 actionable tasks: 15 executed, 2 from cache, 5 up-to-date

```

**Comment by thc202** [comment]
Yes, add it as a `testRuntimeOnly` dependency.

**Comment by kingthorin** [comment]
`    testRuntimeOnly(project("encoder"))` doesn't work.

```bash
$ ./gradlew :addOns:kotlin:test

> Task :buildSrc:jar
:jar: No valid plugin descriptors were found in META-INF/gradle-plugins

> Configure project :addOns:browserView
Project :addOns:browserView => no module-info.java found

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\thorin\Desktop\zap-ws\zap-extensions\addOns\kotlin\kotlin.gradle.kts' line: 30

* What went wrong:
Project with path 'encoder' could not be found in project ':addOns:kotlin'.
```

**Comment by kingthorin** [comment]
Took a number of tries to get the right syntax but I seem to have gotten there :grinning:

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Review by psiinon — APPROVED** [review]

**Pull request merged**
