### PR TITLE
Added unit test for InsecureAuthenticationScanUnitTest

### PR DESCRIPTION
**Pull request by rscipien**
Test for issue [2806](https://github.com/zaproxy/zaproxy/issues/2806)

### CODE REVIEW

**Comment by rscipien** [comment]
Fixed

**Comment by kingthorin** [comment]
TODO:

- [ ]  Fix conflicts

**Comment by kingthorin** [comment]
@psiinon, leaving to you for merge since I ended up working on it.

**Comment by thc202** [comment]
@rscipien thanks!

**Pull request merged**
