### PR TITLE
encoder: Prepare next dev iteration

### PR DESCRIPTION
**Pull request by kingthorin**
- Update version and changelog.
- Promote to beta.
- Add agreed info URL for manifest.

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
There's a check stuck.

**Comment by kingthorin** [comment]
Seems to be a Travis status reporting issue. They actually completed with success. If it doesn't sort itself shortly I'll kick it with a useless amend.

**Comment by thc202** [comment]
I don't think it will (it didn't in other cases), it might be enough with closing/opening the PR though.

**Comment by thc202** [comment]
It wasn't... :/

**Comment by kingthorin** [comment]
Amend kick seems to have worked.

**Review by psiinon — APPROVED** [review]

**Pull request merged**
