### PR TITLE
reports: added JSON report template that includes requests and responses

### PR DESCRIPTION
**Pull request by jeremychoi**
Similarly with the _HTML report with requests and responses_ template, this adds a JSON report template that includes requests and responses.

### CODE REVIEW

**Comment by psiinon** [comment]
Thanks for submitting this :)
One option would be for this report to support sections, which would make it easier to extend.
Thoughts @thc202 @kingthorin ?

**Comment by kingthorin** [comment]
To address the DCO requirement you'll need to sign-off the commit(s):

- https://github.com/zaproxy/zaproxy/blob/develop/CONTRIBUTING.md#developer-certificate-of-origin
- https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff

**Comment by kingthorin** [comment]
@jeremychoi are you planning to finish this?

**Comment by jeremychoi** [comment]
@kingthorin thanks for the heads up. i've amended my commit with sign-off. Please let me know if there's something more to be done.

**Comment by jeremychoi** [comment]
not really. the commit is simply for the full JSON report

**Comment by psiinon** [comment]
I'm good with this as it stands, and I'd be happy to update it to support sections prior to us releasing it :)

**Review by psiinon — APPROVED** [review]

**Review by kingthorin — APPROVED** [review]

**Comment by thc202** [comment]
The changelog should be updated at some point.

**Comment by psiinon** [comment]
I can do that when I add section support😀

**Pull request merged**
