### PR TITLE
Report Competition Template

### PR DESCRIPTION
**Pull request by psiinon**
Submitted on behalf of @Scopestyle so this is still his work and should be considered as a submission for the Reporting Competition.

I've just done some minor tweaks inc the fixes in #2974

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Comment by thc202** [comment]
@Scopestyle what's the license of the images?

**Comment by psiinon** [comment]
Just chatted to @scopestyle via twitter DM, then are from https://unsplash.com/ so free to use :)

**Comment by thc202** [comment]
Great.

**Comment by psiinon** [comment]
Review? @thc202 @kingthorin @ricekot :)

**Review by kingthorin — APPROVED** [review]
LGTM

**Review by thc202 — APPROVED** [review]

**Comment by psiinon** [comment]
As per https://github.com/zaproxy/zap-extensions/pull/2876#issuecomment-827600345 @Scopestyle has bee awarded $200 for this submission to the [Report Competition](https://www.zaproxy.org/blog/2021-03-12-report-competition/) - many thanks!

**Comment by psiinon** [comment]
I've submitted an OWASP Project Reimbursement Request https://owasporg.atlassian.net/servicedesk/customer/portal/4/OSD-4013 (which most people wont have access to;) on behalf of @Scopestyle specifying their paypal acc.
@Scopestyle - can you update this issue when that gets paid to you?

**Comment by Scopestyle** [comment]
Will do, many thanx!

**Comment by psiinon** [comment]
@Scopestyle have you received this payment yet?

**Comment by Scopestyle** [comment]
@psiinon Unfortunately not

**Comment by psiinon** [comment]
I've asked for an update on the ticket...

**Comment by Scopestyle** [comment]
@psiinon OWASP Payment just came trough. Thanx again!

**Pull request merged**
