### PR TITLE
client: add element interactions to the spider

### PR DESCRIPTION
**Pull request by thc202**
Fill input elements.
Click reported elements.
Submit reported forms.

### CODE REVIEW

**Comment by psiinon** [comment]
Logo
**Checkmarx One – Scan Summary & Details** – [d4316197\-2f04\-4ee9\-bae2\-3f6f8d1c6a03](https://eu.ast.checkmarx.net/projects/0da811fa-6373-42b1-bbb6-d0026285b136/scans?id=d4316197-2f04-4ee9-bae2-3f6f8d1c6a03&branch=thc202%2Fclient%2Fspider%2Felements)
### No New Or Fixed Issues Found

**Comment by thc202** [comment]
Rebased to pick #6020 and fixed other test that was failing.

**Comment by thc202** [comment]
Rebased to pick #6018, should now be easier to test.

**Review by psiinon — APPROVED** [review]

**Comment by thc202** [comment]
Addressed conflicts.

**Review by kingthorin — APPROVED** [review]

**Comment by kingthorin** [comment]
🕷️🎉

**Pull request merged**
