### PR TITLE
testutils: sync ping in WebSocket test server

### PR DESCRIPTION
**Pull request by thc202**
Sync ping to make sure the internal state is consistent when checking
if expected pong was received.
Addresses intermittent failure in WebSocket ping/pong test.

### CODE REVIEW

**Review by psiinon — APPROVED** [review]

**Review by kingthorin — APPROVED** [review]

**Comment by thc202** [comment]
This does not address the problem, still checking...

**Comment by thc202** [comment]
Pull request updated, the issue was in testutils. Should be ready for another review.

**Review by psiinon — APPROVED** [review]
Still looks good to me :D

**Review by kingthorin — APPROVED** [review]
Thanks!

**Pull request merged**
