### PR TITLE
Latest files from Crowdin

### PR DESCRIPTION
**Pull request by zapbot**
Autogenerated PR from zapbot

### CODE REVIEW

**Comment by kingthorin** [comment]
Don't merge this one:
https://github.com/zaproxy/zap-extensions/pull/1026/commits/f844eda55105a1d5ae12f00f3d1c2772c91e1547#diff-313676c4e3e3362a3bad17dc040b8255R140

**Comment by kingthorin** [comment]
Fixed on crowdin

**Comment by thc202** [comment]
Thanks! Spotted other similar issues (already fixed in Crowdin):
https://github.com/zaproxy/zap-extensions/commit/f844eda55105a1d5ae12f00f3d1c2772c91e1547#diff-10742430ea4e162253daba1635c17eeeR56
https://github.com/zaproxy/zap-extensions/commit/f844eda55105a1d5ae12f00f3d1c2772c91e1547#diff-10742430ea4e162253daba1635c17eeeR62
https://github.com/zaproxy/zap-extensions/commit/f844eda55105a1d5ae12f00f3d1c2772c91e1547#diff-10742430ea4e162253daba1635c17eeeR71
https://github.com/zaproxy/zap-extensions/commit/f844eda55105a1d5ae12f00f3d1c2772c91e1547#diff-10742430ea4e162253daba1635c17eeeR119

**Comment by kingthorin** [comment]
Tks @thc202

**Pull request closed without merging**
