### PR TITLE
Issue 2174 - Handle Previously Uncaught Exceptions

### PR DESCRIPTION
**Pull request by kingthorin**
Added try/catch block around sendAndReceive for exceptions identified
via zapbot automated wavsep testing.

Fixes zaproxy/zaproxy#2174

### CODE REVIEW

**Comment by thc202** [comment]
Thanks.

**Comment by thc202** [comment]
Recalled now :/ that we need to bump the version of the add-on (and remove old changes).
Should I go ahead with those changes?

**Comment by kingthorin** [comment]
Sure or I can do another PR with them tonight, just let me know.

**Comment by thc202** [comment]
OK, opened a PR: #231.

**Pull request merged**
