### PR TITLE
GraphQl: dont report errors parsing valid JSON

### PR DESCRIPTION
**Pull request by psiinon**
I'm testing a site that has APIs which all seem to return JSON Arrays.
The logging is not just annoying - its INFO level and I'm getting so many that its seriously impacting performance :/
If its not an error or warning then it should be logged at debug level, especially for variants which get invoked so many times.

### CODE REVIEW

**Review by kingthorin — COMMENTED** [review]
Tests?

Otherwise looks good.

**Comment by psiinon** [comment]
Not sure how easy it will be to test if log4j has logged an error ... but I'll see..

**Comment by kingthorin** [comment]
I was thinking more that a message which is an array is actually handled.

**Comment by psiinon** [comment]
Its not actually handled :) We just dont log an error...

**Comment by psiinon** [comment]
I dont think the responses are valid graphql , but they are JSON.
There is no graphql query to extract...

**Comment by psiinon** [comment]
No, thats just so we dont even log debug messages if its a valid JSON array

**Review by kingthorin — APPROVED** [review]

**Comment by psiinon** [comment]
Added a couple of unit tests 😁

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
