### PR TITLE
Getting started: add macOS workaround

### PR DESCRIPTION
**Pull request by psiinon**
Screenshot 2022-10-17 at 10 38 10

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]
Thanks

**Comment by psiinon** [comment]
Changed to always use "macOS"

Screenshot 2022-10-17 at 15 33 12

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Comment by kingthorin** [comment]
Could we get the website PR merged as well pls 😀 https://github.com/zaproxy/zaproxy-website/pull/1354

**Pull request merged**
