### PR TITLE
Depend on gradle-plugin-common

### PR DESCRIPTION
**Pull request by ricekot**
Also run spotlessPropertiesApply once.

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]
Nice!

**Comment by kingthorin** [comment]
Seems to be getting upset in the reports addon for some reason.

**Review by kingthorin — APPROVED** [review]
Thanks!

**Comment by thc202** [comment]
Could you rebase this?

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
