### PR TITLE
Latest files from Crowdin

### PR DESCRIPTION
**Pull request by zapbot**
Autogenerated PR from zapbot

### CODE REVIEW

**Comment by kingthorin** [comment]
Two out if three sets of square brackets dropped?

**Comment by thc202** [comment]
@3bhady a typo?

**Comment by kingthorin** [comment]
?

**Comment by thc202** [comment]
https://crowdin.com/project/owasp-zap/activity_stream

**Comment by kingthorin** [comment]
Cool, nice catch.

**Pull request closed without merging**
