### PR TITLE
pscanrulesAlpha Address Deprecations

### PR DESCRIPTION
**Pull request by kingthorin**
Fix use of getLevel.

### CODE REVIEW

**Comment by kingthorin** [comment]
Do I need to set not-before to 2.7.0 for all these?

**Comment by thc202** [comment]
Yes, those methods are only available in the newer version.

**Comment by kingthorin** [comment]
Ok I’ll update the manifest further on all 5 PRs

**Comment by kingthorin** [comment]
Done x5

**Comment by thc202** [comment]
Thanks! x5 :)

**Pull request merged**
