### PR TITLE
Httpsinfo: automation 

### PR DESCRIPTION
**Pull request by cerskus**
Based on wappalyzer addon: 
- Added HttpsInfoAutomation extension
- Updated panel
- Implemented httpsinfoScanner as passive scanner instead of threaded task

### CODE REVIEW

**Comment by thc202** [comment]
Ref zaproxy/zaproxy#6918.

**Comment by cerskus** [comment]
> 
> 
> Ref [zaproxy/zaproxy#6918](https://github.com/zaproxy/zaproxy/issues/6918).

For my current use-cases, CipherSuites is not needed. As far as retrieved certification is correct I'm fine sticking to deepviolet.

**Comment by kingthorin** [comment]
@cerskus if you have any interest in maintaining this going forward it could be split off into a 3rd party add-on.

We do have a process in place to have 3rd party add-ons published via the ZAP Marketplace, and you might be able to talk spoofzu into fixing/continuing [DeepViolet](https://github.com/spoofzu/DeepViolet/issues/332)

**Comment by kingthorin** [comment]
Closing per above updates. Please let us know if you plan to take the add-on(s) third party.

**Pull request closed without merging**
