### PR TITLE
retire.js Update 2021-06-02

### PR DESCRIPTION
**Pull request by zapbot**
Updates based on RetireJS/retire.js@5cea608

Signed-off-by: zapbot <12745184+zapbot@users.noreply.github.com>

### CODE REVIEW

**Review by psiinon — APPROVED** [review]

**Comment by thc202** [comment]
Closing, this was already merged.

**Comment by kingthorin** [comment]
I guess that's because zapbot's repos aren't updated? 
https://github.com/zapbot/zap-extensions

We could include a step in the workflows to update the origin repo, before putting things together.

**Comment by kingthorin** [comment]
Actually what makes you think this was already merged?

**Comment by thc202** [comment]
Per https://github.com/zaproxy/zap-extensions/commit/b49389f9f6520cf3007b781231fa732391379cb9

The pull request is not shown as merged because of the earlier issues with GitHub (same that happened in zaproxy-website).

**Comment by kingthorin** [comment]
Oh I didn't realize it was a "today" issue, when you said "already merged" I was thinking you meant like in last month's workflow or something....

I guess issues are on-going since master doesn't show the updated content?

**Comment by thc202** [comment]
Good question, I'd expect the default branch to show the proper contents given the merge commit shown in the history... but fetching from upstream does not bring that commit either.

According to the status page the issues are now resolved. We might need to contact GitHub support if that does not resolve by itself soon.

**Comment by kingthorin** [comment]
Dunno if I'll get a response, but: https://twitter.com/kingthorin_rm/status/1400064942179602434

If that doesn't go anywhere we can hit up support.

**Comment by thc202** [comment]
Actually seems to be good, a clone and download of source shows the expected content. And I do have that in the history now, maybe it's just the Web UI that didn't update.

**Comment by kingthorin** [comment]
Thanks!

**Pull request closed without merging**
