### PR TITLE
advreport: consolidated cancel and generate buttons under one class

### PR DESCRIPTION
**Pull request by skhakimov**
To avoid repetition across multiple panels, moved 'Cancel' and 'Generate HTML' buttons under the class ExtensionAdvReport.java

### CODE REVIEW

**Comment by thc202** [comment]
This one is a good catch ;)
It's better to move the buttons to OptionDialog instead (to a new JPanel, parent of JTabbedPane), the (inner) panels would no longer have the responsibility to add the buttons and it would also normalise its position (which is different in ScopePanel than AlertsPanel/AlertDetailsPanel).

**Comment by skhakimov** [comment]
Thanks for the suggestion,  will move them.

**Comment by skhakimov** [comment]
Hi,

I made changes based on your feedback.  Thanks.

**Comment by thc202** [comment]
Thank you.

**Pull request merged**
