### PR TITLE
Quickstart: Generate quickout reports using the reports add-on instead of the core

### PR DESCRIPTION
**Pull request by psiinon**
Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]

**Comment by psiinon** [comment]
Arg, this depends on some other changes - I split them out to make it easier to review :/

**Comment by psiinon** [comment]
Have added in the enabling changes in reports, so fingers crossed it builds this time ;)

**Comment by psiinon** [comment]
Tests pass now :)

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Review by kingthorin — APPROVED** [review]
Thanks

**Pull request merged**
