### PR TITLE
oast: Showing state indicator for current ActiveScanOastService

### PR DESCRIPTION
**Pull request by denniskniep**
Currently there is not good way how to determine if the OAST Service is working or not. You can not distinguish between error in oast server/client and that no payload triggered. You have to look for errors in the logfile. 

None Selected
image

Not Connected
image

IsRegistered and additionally the last poll time
image

Signed-off-by: Dennis Kniep <kniepdennis@gmail.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
Neat idea.
Shouldn't "No Service" be red?

**Comment by denniskniep** [comment]
> Neat idea. Shouldn't "No Service" be red?

It is at least a valid option 
image

Therefore it should not be an "error" case, should'n it?

**Comment by kingthorin** [comment]
Okay, fair, maybe it's just a terminology tweak then: "None Selected"  ?

'No service' seems like some sort of error state to me. (Like if my cell phone has "No service" :wink:)

**Comment by denniskniep** [comment]
yeah, but the active scan service is probably the interesting one, right?
Does not seem likely that some one is switching OAST services back and forth between zap start and shutdown.
Displaying all services in the toolbar would probably be too much.

To be precise  we can add the prefix "Active Scan Service:"

**Comment by thc202** [comment]
Before the active scan service was added we got feedback from users that were using the add-on for manual pentesting, I guess the state of those services would be useful too in that case. (Not asking for changes just adding info.)

**Comment by denniskniep** [comment]
> were using the add-on for manual pentesting

But they were using probably only one service for manual pentesting, right? Not mixing the services like generating one payloady with BOAST and another one with InteractSh?

Is it ready for merge?

**Comment by thc202** [comment]
That I don't know.

**Comment by ricekot** [comment]
What do you all think about this approach? This way we can show all services.

zap-oast-status-2

**Comment by thc202** [comment]
Looks good to me.

**Comment by kingthorin** [comment]
Yup, that makes sense.

**Comment by denniskniep** [comment]
Generally red indicator means to me that there is something not working or wrong. This could be misleading if I use InteractSh as  ActiveScanService which is registered and polling (green). BOAST has a red indicator, due to its not registered (because I don't want to use it) which is in that case fine and means no error.

I propose the following if we want to have a status indication of  all OAST Services in the toolbar:
* IsActiveScanService && NotRegistered = Red
* NotActiveScanService && NotRegistered = Gray
* IsRegistered = Green with last polltime

And the tooltip may also be extended for the  ActiveScanService.

**Comment by ricekot** [comment]
zap-oast-status-3

**Comment by kingthorin** [comment]
I like it 👍

**Comment by denniskniep** [comment]
@ricekot looks really good

**Review by kingthorin — APPROVED** [review]

**Review by psiinon — APPROVED** [review]

**Comment by thc202** [comment]
There's a pending tweak.

**Comment by thc202** [comment]
Thank you both!

**Pull request merged**
