### PR TITLE
webuipoc: Display request method with leaf nodes

### PR DESCRIPTION
**Pull request by Moeez905**
WIP issue https://github.com/zaproxy/zaproxy/issues/8287

### CODE REVIEW

**Comment by njmulsqb** [comment]
@Moeez905 Fix your description as stated in https://github.com/zaproxy/zaproxy/issues/8287#issuecomment-2241945537

**Comment by psiinon** [comment]
Is this ready to review?
I'm not seeing any methods displayed :/

**Comment by thc202** [comment]
This PR is still including #5588.

**Comment by Moeez905** [comment]
> Is this ready to review? I'm not seeing any methods displayed :/

image

if I'm not wrong its showing methods I.E GET in this case

**Comment by Moeez905** [comment]
> This PR is still including #5588.

My bad, our main branch fork wasn't synced at the time of making this new branch I believe, thats why it fetched previous commits too,
Do I need to close this commit and make a new one with new branch?

**Comment by thc202** [comment]
No, just remove the other unrelated commits.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
See https://github.com/zaproxy/zap-extensions/pull/5624#discussion_r1703631494

Thank you!

**Review by psiinon — APPROVED** [review]

**Pull request merged**
