### PR TITLE
Wappalyzer Update 2022-02-27

### PR DESCRIPTION
**Pull request by zapbot**
Updates based on AliasIO/Wappalyzer@c9950a1

Signed-off-by: zapbot <12745184+zapbot@users.noreply.github.com>

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]

**Comment by thc202** [comment]
One of the expressions is breaking the build.

**Comment by kingthorin** [comment]
Tks, will check.

**Comment by kingthorin** [comment]
Fixed

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
