### PR TITLE
improve: Unit Test related SAST (sonar) findings

### PR DESCRIPTION
**Pull request by kingthorin**
- automation, ascanrulesBeta, openapi > Ensure Unit Tests have assertions.
- alertFilters, ascanrules, ascanrulesAlpha, ascanrulesBeta, automation, bruteforce, domxss, frontendscanner, fuzz, graphql, imagelocationscanner, kotlin, openapi, pscanrules, pscanrulesAlpha, pscanrulesBeta, replacer, reports retire, selecium, soap, spiderAjax, sse, testutils, tokengen, wappalyzer, websocket, zest > Remove public modifier on JUnit test, before, etc methods.
- ascanrules, ascanrulesBeta, fuzz > ensure assertThrows lambdas only execute a single method (extract variables to given blocks for indirectly related work).
- graphql, websocket, retire, soap, pscanrules, wappalyzer > Replace use of assertTrue and assertFalse containing equality or  nequality tests with use of assertEquals or assertNotEquals with the relevant values.

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by thc202** [comment]
Changes done to tests do not affect the built add-on so does not require updating the changelog.

The public modifiers of the classes can be removed as well. Some before/after each/all methods were missed.

**Comment by kingthorin** [comment]
Should  `addOns/automation/add-ons-state.xml` be added to .gitignore?

**Comment by thc202** [comment]
No, the test should be changed to use a temp ZAP home (like other tests do).

**Comment by kingthorin** [comment]
For this PR how do I remove it?

**Comment by thc202** [comment]
Do `git rm addOns/automation/add-ons-state.xml` and amend the commit.

**Comment by kingthorin** [comment]
I've done all the classes, befores, and afters.

I didn't change the unittest in bruteforce, wasn't sure if I should.
I also left a few things like the abstracts in commonlib and the use of them because I ended up with build issues. Also one item in websocket I left an after as public because of build problems.

**Comment by thc202** [comment]
Yeah, not all classes should change (e.g. base classes).

**Comment by kingthorin** [comment]
spotless applies and reverted the testutils change :zap:

**Comment by thc202** [comment]
The latest PRs no longer mention the tool that reported the issues, for attribution and the record they should.

**Comment by kingthorin** [comment]
They’re all sonar, I’ll update commit/PR messages

**Comment by thc202** [comment]
Thank you!

**Comment by kingthorin** [comment]
Done

**Comment by thc202** [comment]
The classes `ActiveScannerTest` and `PassiveScannerTest` can be package accessible too, those are only to be used by the tests of the add-ons.

The following classes still require changes:
 - `EnvFileScanRuleUnitTest`
 - `HiddenFilesScanRuleUnitTest`
 - `SourceCodeDisclosureCve20121823ScanRuleUnitTest`
 - `TraceAxdScanRuleUnitTest`
 - `XxeScanRuleUnitTest`
 - `ActiveScanJobUnitTest`
 - `PassiveScanConfigJobUnitTest`
 - `PassiveScanJobResultsUnitTest`
 - `PassiveScanWaitJobUnitTest`
 - `SpiderJobUnitTest`
 - `EasySSLProtocolSocketFactoryUnitTest` (it's fine to change it)
 - `CookieUtilsUnitTest`
 - `FrontEndScannerProxyListenerUnitTest`
 - `InfoSessionIdUrlScanRuleUnitTest`
 - `AjaxSpiderJobUnitTest`
 - `BaseEventStreamTest`

**Comment by thc202** [comment]
The removal of the modifiers could have been done in its own commit to make the other changes easier to review.

**Comment by thc202** [comment]
btw, after (or before) merging this we should ensure open PRs do not introduce public modifiers.

**Comment by kingthorin** [comment]
> The removal of the modifiers could have been done in its own commit to make the other changes easier to review.

Sorry about that.

**Comment by kingthorin** [comment]
I wasn't able to do these because they're based on abstract classes in another add-on. Even if I changed the method signature there I'd still have build issues 😢 
`EnvFileScanRuleUnitTest`
`HiddenFilesScanRuleUnitTest`
`TraceAxdScanRuleUnitTest`

**Comment by thc202** [comment]
You are referring to the ones that are overriding, I was talking about the ones that don't.

**Comment by kingthorin** [comment]
Done

**Comment by thc202** [comment]
The class modifier of `EasySSLProtocolSocketFactoryUnitTest` was not removed.

**Comment by kingthorin** [comment]
Thanks for catching that, tweaked the commit/PR message to include bruteforce as well.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Review by psiinon — APPROVED** [review]

**Pull request merged**
