### PR TITLE
[Alpha extension] SOAP Scanner fix: operations with the same location were overwritten in the sites tree.

### PR DESCRIPTION
**Pull request by Albertov91**
This is the continuation of a previous pull request: https://github.com/zaproxy/zap-extensions/pull/30
I have fixed most of the things indicated there. However, no solution comes to my mind about preserving the fix when reopening sessions without making modifications outside the plugin.

### CODE REVIEW

**Comment by thc202** [comment]
Yeah, the fix might require core changes. Could you raise an issue in zaproxy repo about this issue?

**Comment by thc202** [comment]
Thank you.

**Comment by Albertov91** [comment]
Thank you for merging :)
I have raised the issue regarding the overwriting problem here: https://github.com/zaproxy/zaproxy/issues/1867

**Comment by thc202** [comment]
Thanks!

**Pull request merged**
