### PR TITLE
Remove VulnCheck add-on

### PR DESCRIPTION
**Pull request by theamanrawat**
Fixes zaproxy/zaproxy#6364

Signed-off-by: Aman Rawat <35992750+theamanrawat@users.noreply.github.com>

### CODE REVIEW

**Comment by thc202** [comment]
You can close the issue as well: https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

**Comment by theamanrawat** [comment]
> You can close the issue as well: https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

Done. Thanks for this.

**Review by kingthorin — APPROVED** [review]
Tks!

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thanks!

**Pull request merged**
