### PR TITLE
issue-823-i18n-active-passive-scan-rules-alpha

### PR DESCRIPTION
**Pull request by kingthorin**
Fixes zaproxy/zaproxy#823

### CODE REVIEW

**Comment by thc202** [comment]
What do you think of removing the Vulnerability from this scanner? We would just need to add the references to Messages.properties file (which could be shared with SVN scanner).

**Comment by thc202** [comment]
SVN is in beta so not much sharing... for now.

**Comment by thc202** [comment]
Should I go ahead with the merge? (i.e. the refs are still obtained with Vulnerability)

**Comment by kingthorin** [comment]
Yes.

If we want to totally get away from using vulnerability as a source of alert details that will have to be handled via a separate issue (IMHO).

Also there are some plugins (across all 3 qualities) which still have TODO items on WASC and CWE IDs which I did not address as part of [issue #823](https://github.com/zaproxy/zaproxy/issues/823) if the plugin was already i18n'd. I plan to raise another issue and handle those updates separately.

**Comment by thc202** [comment]
OK.

**Comment by thc202** [comment]
Thanks!

Regarding the usage of Vulnerability, it's not a general change it was just for this case(s) were it's just used to obtain the references (better have related information in the same place than split between the add-on and core). For the cases were it's used for everything (name, desc, soln, refs) there's no need to change.

**Pull request merged**
