### PR TITLE
automation: allow to include techs

### PR DESCRIPTION
**Pull request by thc202**
Allow to target specific techs without requiring to exclude all the other ones supported.

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]

**Review by kingthorin — APPROVED** [review]

**Review by kingthorin — APPROVED** [review]

**Review by kingthorin — APPROVED** [review]

**Comment by thc202** [comment]
Addressed IRC feedback, include children for proper display in the tech tree.

**Review by kingthorin — COMMENTED** [review]
Does this depend on current core changes now?

**Comment by thc202** [comment]
No.

**Comment by kingthorin** [comment]
Okay, still good with me then 👍

**Review by kingthorin — APPROVED** [review]

**Review by psiinon — APPROVED** [review]

**Pull request merged**
