### PR TITLE
encoder: Simplify hash processors

### PR DESCRIPTION
**Pull request by kingthorin**
- CHANGELOG > Add change note.
- HashProcessor > Added class with generic handling.
- Md5Hasher, Sha1Hasher, Sha256Hasher > Extend HashProcessor and are now singletons.
- Predefined processors > Implement singletons.
- EncodeDecodeProcessors > Updated to use the new singletons.

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
Note: I'll rebase my testing branch on top of this once merged.

This simplifies adding other hashers in the future.

**Comment by thc202** [comment]
This breaks compatibility.

**Comment by kingthorin** [comment]
I’ll roll the major version then?

**Comment by kingthorin** [comment]
Or leave the existing 3 and keep this for future use?

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Comment by kingthorin** [comment]
Is it worth adding a template script such as:

```
var EncodeDecodeResult = Java.type("org.zaproxy.addon.encoder.processors.EncodeDecodeResult");
// Get the predefined Md5 hash processor
var processor = Java.type("org.zaproxy.addon.encoder.processors.predefined.Md5Hasher").getSingleton();

/**
 * Use the predefined md5 processor, then lower case it's output.
 *
 * @param {String} value - The input value
 * @returns {EncodeDecodeResult} - The value that was encoded/decoded/hashed etc.
 */
function process(value){
	var output = processor.process(value).getResult();
	return new EncodeDecodeResult(output.toLowerCase());
}
```

**Comment by kingthorin** [comment]
That question can be ignored. As discussed elsewhere it’ll make more sense to add a helper object and provide predefined processors through that.

**Review by psiinon — APPROVED** [review]

**Pull request merged**
