### PR TITLE
Reports: Fix alert counts to ignore false positives

### PR DESCRIPTION
**Pull request by psiinon**
Found while adding integration tests for zaproxy/zaproxy#6781 

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

LGTM continues to fail, still trying to use `jcenter`...

**Comment by psiinon** [comment]
Ugh :/

**Review by kingthorin — APPROVED** [review]

**Comment by kingthorin** [comment]
Okay to merge ignoring the LGTM issue?

**Comment by psiinon** [comment]
Yep :)

**Pull request merged**
