### PR TITLE
Automation: Fix var support in URLs

### PR DESCRIPTION
**Pull request by psiinon**
Fixes: https://github.com/zaproxy/zaproxy/issues/6726)

Mostly tested manually as automation jobs are hard to unit test :/

Also supports env in requestor data and improved some of the info messages to inc URLs.

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Comment by psiinon** [comment]
Ugh, looking at the tests now...

**Comment by psiinon** [comment]
Tests passed, so should be good to review :)

**Review by kingthorin — APPROVED** [review]
LGTM

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
