### PR TITLE
Client: spider, first phase

### PR DESCRIPTION
**Pull request by psiinon**
## Overview
First phase of the new client spider. Not for release at this stage.

It can be tested using a ZAP standalone scripts like:
```
var extClient = control.getExtensionLoader().getExtension("ExtensionClientIntegration");
print(extClient.runSpider('http://localhost:3000/', "firefox", 4, 5, 2, 5));
print(extClient.getSpider(0).getProgress());
```

## Checklist
- [ ] Update help
- [ ] Update changelog
- [x] Run `./gradlew spotlessApply` for code formatting
- [x] Write tests
- [x] Check code coverage
- [x] Sign-off commits
- [x] Squash commits
- [x] Use a descriptive title

For more details, please refer to the [developer rules and guidelines](https://www.zaproxy.org/docs/developer/dev-rules-and-guidelines/).

### CODE REVIEW

**Comment by psiinon** [comment]
Ugh, tested the new code in isolation, but it broke the existing unit tests 😉 
Will fix..

**Comment by psiinon** [comment]
Fixed

**Review by kingthorin — COMMENTED** [review]
Haven't tested but seems okay overall

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Comment by psiinon** [comment]
Hopefully all done now

**Review by kingthorin — APPROVED** [review]

**Pull request merged**
