### PR TITLE
jython/groovy/graaljs: Add/move encode-decode Default and rot13 Templates 

### PR DESCRIPTION
**Pull request by kingthorin**
In follow-up to:
https://stackoverflow.com/questions/66567325/how-to-access-encodedecoderesult-from-jython-zap

I also looked at adding a Ruby remplate but apparently jruby isn't compatible with JDK 11.
```
36277 [ZAP-ScriptExecutor-sd] ERROR org.zaproxy.zap.ZAP.UncaughtExceptionLogger - Exception in thread "ZAP-ScriptExecutor-sd"
java.lang.ExceptionInInitializerError: null
	at org.jruby.embed.internal.AbstractLocalContextProvider.<init>(AbstractLocalContextProvider.java:42) ~[?:?]
	at org.jruby.embed.internal.SingletonLocalContextProvider.<init>(SingletonLocalContextProvider.java:88) ~[?:?]
	at org.jruby.embed.ScriptingContainer.getProviderInstance(ScriptingContainer.java:246) ~[?:?]
	at org.jruby.embed.ScriptingContainer.<init>(ScriptingContainer.java:226) ~[?:?]
	at org.jruby.embed.jsr223.JRubyEngineFactory.getScriptEngine(JRubyEngineFactory.java:170) ~[?:?]
	at org.zaproxy.zap.extension.script.ScriptEngineWrapper.getEngine(ScriptEngineWrapper.java:63) ~[main/:?]
	at org.zaproxy.zap.extension.script.ExtensionScript.invokeScriptImpl(ExtensionScript.java:1491) ~[main/:?]
	at org.zaproxy.zap.extension.script.ExtensionScript.invokeScript(ExtensionScript.java:1439) ~[main/:?]
	at org.zaproxy.zap.extension.scripts.ConsolePanel$ScriptExecutorThread.run(ConsolePanel.java:616) ~[?:?]
Caused by: java.lang.RuntimeException: unsupported Java version: 11
	at org.jruby.RubyInstanceConfig.initGlobalJavaVersion(RubyInstanceConfig.java:1693) ~[?:?]
	at org.jruby.RubyInstanceConfig.<clinit>(RubyInstanceConfig.java:1398) ~[?:?]
```

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by thc202** [comment]
IMO this should be added to the Jython add-on. (We usually just bundled templates for the "default" engine in the add-on that provides the respective functionality, which we should stop doing soon, when Nashorn is gone.)

**Comment by kingthorin** [comment]
Okay I’ll shift it.

**Comment by kingthorin** [comment]
Shall I migrate the groovy default template as well?

**Comment by thc202** [comment]
Sounds good to me.

**Comment by kingthorin** [comment]
Done

**Comment by kingthorin** [comment]
Done again 😀

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Review by psiinon — APPROVED** [review]

**Pull request merged**
