### PR TITLE
advreport: added internationalization

### PR DESCRIPTION
**Pull request by skhakimov**
Added internationalization and the Messages.properties file to the advreport extension.

### CODE REVIEW

**Comment by thc202** [comment]
Just noticed that there are 3 strings not yet internationalised in class ScopePanel, sorry.
The buttons "Cancel" and "Generate HTML" and the checkbox "Only contents in scope?".
Would you mind changing that in this PR?

**Comment by skhakimov** [comment]
Good Catch!  Added those strings as well.

**Comment by thc202** [comment]
Nice. Could you fix up the commit?

**Comment by thc202** [comment]
Thanks!

**Pull request merged**
