### PR TITLE
FuzzDB Extension

### PR DESCRIPTION
**Pull request by amuntner**
Made the edits discussed previously[1]: changing the description text. replacing the spaces with tabs, removing the old directories.

Tested it by making my own .zap exension zip/jarfile with the new XML and fuzz files, all worked as expected. 

1. https://github.com/zaproxy/zap-extensions/pull/40

### CODE REVIEW

**Comment by thc202** [comment]
Would you mind fixup the commits?
There are still indentation changes in the first edited lines of `ZapAddOn.xml`.
Note that you can update this pull request with new changes.

**Comment by amuntner** [comment]
Thank you, should be fixed now.

**Comment by thc202** [comment]
Changes look good, just remaining the fixup of the commits.

**Comment by amuntner** [comment]
Thank you. Not sure what you're asking me to do, though?

**Comment by thc202** [comment]
Fold commits into one. [1]

[1] https://www.kernel.org/pub/software/scm/git/docs/git-rebase.html#_interactive_mode

**Comment by thc202** [comment]
@amuntner is there anything that I can do to help with the fixup?

**Comment by kingthorin** [comment]
@amuntner is a fixup in the works?

**Comment by amuntner** [comment]
Yes, this week. Thanks for the reminder!

**Comment by kingthorin** [comment]
@amuntner ping :smile:

**Comment by kingthorin** [comment]
@amuntner is a fixup in the works?

**Comment by kingthorin** [comment]
@amuntner any news?

**Comment by amuntner** [comment]
I haven't had the bandwidth to get to it, as much as I would love to,

Could someone else take on making the new addon please? This would be a
good time, I added a lot of payloads recently and just today there was a
file renaming update: no more .fuzz.txt just .txt, also consistent
directory name formatting.

**Comment by thc202** [comment]
@amuntner opened #385, let me know if the commit used (and overall changes) is correct.

**Comment by kingthorin** [comment]
Closing, see https://github.com/zaproxy/zap-extensions/pull/385

**Pull request closed without merging**
