### PR TITLE
ascanrulesBeta: add missing file

### PR DESCRIPTION
**Pull request by thc202**
Move the file `hidden_files.json` from `ascanrulesAlpha` to
`ascanrulesBeta`, missed during the promotion.

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]
TY!

**Review by psiinon — APPROVED** [review]

**Comment by psiinon** [comment]
All good but now has conflicts.

**Comment by thc202** [comment]
Conflict addressed.

**Review by kingthorin — APPROVED** [review]
Still seems good to me. Thanks!

**Pull request merged**
