### PR TITLE
Added usage message in the httpsinfo extension

### PR DESCRIPTION
**Pull request by Infernalbronco**

### CODE REVIEW

**Comment by Infernalbronco** [comment]
Sorry but I am not familiar with pull requests that much. Can someone help me with this unsuccessful checks?

**Comment by Infernalbronco** [comment]
Signed-off-by: Akshay Mall akshay.98mall@gmail.com

**Comment by thc202** [comment]
The Travis CI check is failing because of the formatting, you can fix it by running the Gradle task `spotlessApply`. For DCO check there's instructions in https://github.com/zaproxy/zap-extensions/pull/2577/checks?check_run_id=1273639800

**Comment by Infernalbronco** [comment]
Thank you for the help. Will try them out.

**Comment by kingthorin** [comment]
Let us know what you're having trouble with and we can help you out.

**Comment by Infernalbronco** [comment]
I was trying to push the project to github directly from the intellij. When I committed earlier it was not signed-off then I saw the option to sign-off in intellij but by mistake merged my modified code with the old code and committed that did not notice it got changed. Sorry for the trouble you, I am not used to github.

**Comment by Infernalbronco** [comment]
I was able to commit the modified code back to my local repo on github. So should I continue with this PR or should create a new one?

**Comment by kingthorin** [comment]
This PR is no longer associated with any branch so probably just start a new one.

**Pull request closed without merging**
