### PR TITLE
Add Job Name field in AjaxSpider Automation dialogue

### PR DESCRIPTION
**Pull request by amankumarchagti**

### CODE REVIEW

**Comment by amankumarchagti** [comment]
@psiinon Sorry, I did changes from Github UI rather than CLI. I hope Everything is fine now.

**Comment by thc202** [comment]
These are still pending: https://github.com/zaproxy/zap-extensions/pull/3091#issuecomment-903257502

**Comment by amankumarchagti** [comment]
@thc202 I ran the command `gradlew spotlessApply`

**Comment by kingthorin** [comment]
Maybe your IDE is trying to enforce some sort of code style?

**Comment by thc202** [comment]
Did you commit and push the changes? That just formats the code.

**Comment by amankumarchagti** [comment]
yeah, I did commit and push the changes. @thc202

**Comment by amankumarchagti** [comment]
@kingthorin I'm using Eclipse for the dev env. FYI

**Comment by kingthorin** [comment]
Why was this closed again?

**Comment by amankumarchagti** [comment]
@kingthorin sorry, I thought to merge new changes, I need to create new PR. now, i got the flow :)

**Comment by kingthorin** [comment]
Okay, no problem.

**Pull request closed without merging**
