### PR TITLE
DOMXSS: Do not request URLs explicitly excluded from context

### PR DESCRIPTION
**Pull request by psiinon**
## Overview
As per title :)

## Checklist
- [x] Update help
- [x] Update changelog
- [x] Run `./gradlew spotlessApply` for code formatting
- [x] Write tests
- [x] Check code coverage
- [x] Sign-off commits
- [x] Squash commits
- [x] Use a descriptive title

For more details, please refer to the [developer rules and guidelines](https://www.zaproxy.org/docs/developer/dev-rules-and-guidelines/).

### CODE REVIEW

**Comment by psiinon** [comment]
Not sure how to add unit tests for this :/ 
Tested manually and confirmed that URLs excluded from the context are no longer requested.

**Comment by thc202** [comment]
Include style in the test pagesand check the requests do not hit the server?

**Comment by thc202** [comment]
Does it worth mentioning in the help?

**Comment by psiinon** [comment]
With added tests 😁
Hoping they pass 🤞

**Comment by thc202** [comment]
Thank you!

**Review by kingthorin — APPROVED** [review]

**Pull request merged**
