### PR TITLE
Getting Started Guide - updated website links

### PR DESCRIPTION
**Pull request by psiinon**
And removed hotkeys link, no idea why it was there ;)

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Comment by psiinon** [comment]
Corrected the links I missed the first time around ;)

**Comment by kingthorin** [comment]
? The pdf is now deleted and the odt added, nothing else seems to have changed...

**Comment by psiinon** [comment]
You sure? I _think_ its still there, but that might just be me not understanding githubs slightly weird UI...

**Comment by kingthorin** [comment]
Oh ok, I glanced it was all red, my bad.

**Pull request merged**
