### PR TITLE
Remove Community Scripts add-on

### PR DESCRIPTION
**Pull request by thc202**
The add-on will be built from its own repository.
Remove related build tasks.

Part of zaproxy/zaproxy#4948 - Build Community Scripts add-on from
community-scripts repo

---
WIP until the add-on is built from community-scripts.

### CODE REVIEW

**Comment by psiinon** [comment]
This pull request **fixes 403 alerts** when merging 92b11f45c1a44b00400871d4def7f12a3df7b804 into 79391f283813db3ff7a0594a9a7d2989c89d6051 - [view on LGTM.com](https://lgtm.com/projects/g/zaproxy/zap-extensions/rev/pr-005c9351da1c0c71f86b008da7980850659dc85a)

**fixed alerts:**

* 377 for Missing variable declaration
* 11 for Unmatchable dollar in regular expression
* 6 for Use of platform\-specific language features
* 2 for Identical operands
* 2 for Incomplete string escaping or encoding
* 2 for String instead of regular expression
* 1 for Unreachable statement
* 1 for Useless conditional
* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by thc202** [comment]
For the record, most of the above alerts were already addressed in the community-scripts repo.

**Comment by psiinon** [comment]
This pull request **fixes 403 alerts** when merging 92b11f45c1a44b00400871d4def7f12a3df7b804 into 99965e048d0d1e0230d5d3ade4880d7dda221c2c - [view on LGTM.com](https://lgtm.com/projects/g/zaproxy/zap-extensions/rev/pr-0613892394f8a805caf1aedd596ba592d12b5f87)

**fixed alerts:**

* 377 for Missing variable declaration
* 11 for Unmatchable dollar in regular expression
* 6 for Use of platform\-specific language features
* 2 for Identical operands
* 2 for Incomplete string escaping or encoding
* 2 for String instead of regular expression
* 1 for Unreachable statement
* 1 for Useless conditional
* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by thc202** [comment]
The add-on is already being built in its own repo.

**Pull request merged**
