### PR TITLE
Add Error Prone

### PR DESCRIPTION
**Pull request by thc202**
Add Error Prone Gradle plugin.
Enable the checks `MissingOverride` and `WildcardImport`.
Add missing `@Override` annotations and remove wildcard imports.
Update changelogs where needed.

### CODE REVIEW

**Comment by thc202** [comment]
The test failure is unrelated to these changes, will fix in another pull request.

**Review by kingthorin — APPROVED** [review]

**Comment by thc202** [comment]
Done in #3010 hopefully, will rebase once that's merged.

**Comment by thc202** [comment]
Build passing now.

**Review by kingthorin — APPROVED** [review]
Thanks!

**Review by ricekot — APPROVED** [review]
Thank you!

**Pull request merged**
