### PR TITLE
ascanrules: Various alert text fixes (periods and whitespace(s))

### PR DESCRIPTION
**Pull request by kingthorin**
## Overview
- CHANGELOG  > Added fix note.
- Messages.properties > Updated various resource messages.
- CommandInjectionScanRuleUnitTest - Updated to match the new content.

---

* Removed use of period space space (should always be period space between sentences now).
* Removed trailing spaces.
* Added periods.

## Related Issues
Reported via Slack.

## Checklist
- [NA] Update help
- [x] Update changelog
- [x] Run `./gradlew spotlessApply` for code formatting
- [x] Write tests
- [x] Check code coverage
- [x] Sign-off commits
- [x] Squash commits
- [x] Use a descriptive title

### CODE REVIEW

**Comment by kingthorin** [comment]
I just didn't keep looking. I'll go through the file further in a bit.

**Comment by kingthorin** [comment]
Updated:
- Removed use of period space space (should always be period space between sentences now).
- Removed trailing spaces.
- Added periods.

**Comment by thc202** [comment]
Has as conflict.

**Comment by kingthorin** [comment]
Fixed

**Comment by thc202** [comment]
May I suggest also removing space after newline? (There's only one in this file, `\n `.)

**Comment by kingthorin** [comment]
Sure, didn't notice but I'll search.

**Comment by kingthorin** [comment]
Found one of each.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Review by psiinon — APPROVED** [review]

**Pull request merged**
