### PR TITLE
Various Add-ons: Promotions

### PR DESCRIPTION
**Pull request by kingthorin**
- Build files and CHANGELOGs updated.
- Requester updated author in build file, the ZAP team has largely taken over authorship/maintenance.

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by thc202** [comment]
There's a typo in requester, the changelog was not updated.

**Comment by kingthorin** [comment]
Thanks, done and done.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Review by ricekot — APPROVED** [review]
Thanks!

**Pull request merged**
