### PR TITLE
chore: pscanrules: Rename XFO alerts where applicable

### PR DESCRIPTION
**Pull request by kingthorin**
- CHANGELOG > Added change note.
- Messages.properties > Updated with modern browser considerations.
- pscanrules.html > Updated with new details.
- renamed scan rule and unit test classes.

Part of zaproxy/zaproxy#6937

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
I'm happy to squash this after review, I just figured it was best to have the text changes separate from the move of the whole rule's entry.

**Comment by thc202** [comment]
Does it worth rename the class (and other resources) as well?

**Comment by kingthorin** [comment]
I wasn’t sure. If you feel like that’s the right move just let me know. I don’t mind tackling that as well.

**Comment by thc202** [comment]
For consistency might be better.

**Comment by kingthorin** [comment]
Did that as a separate commit for simplified review as well.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Comment by ricekot** [comment]
LGTM. @kingthorin can you squash the commits?

**Review by psiinon — APPROVED** [review]

**Comment by kingthorin** [comment]
Will squash shortly

**Review by ricekot — APPROVED** [review]
Thank you!

**Pull request merged**
