### PR TITLE
ascanrules: Path Traversal Check 5 and Other Info adjustments

### PR DESCRIPTION
**Pull request by kingthorin**
- PathTraversalScanRule > Only do "check 5" at Low Threshold, add "Check #" reference to Other info field (to facilitate future user inquiries).
- PathTraversalScanRuleUnitTests > Add assertions for Other info field.
- Messages.properties > Add Other info pair.
- CHANGELOG > Add change notes.

* Fixes zaproxy/zaproxy#4209
* Fixes zaproxy/zaproxy#6030
* Fixes zaproxy/zaproxy#6219
* Fixes zaproxy/zaproxy#6372
* Fixes zaproxy/zaproxy#6380

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
Updated to clarify the "Other info" CHANGELOG note.

**Review by psiinon — APPROVED** [review]

**Comment by thc202** [comment]
The help should be updated and the new condition tested.

**Comment by kingthorin** [comment]
Help tweaked, unit test additions coming (probably not till sometime next week).

**Comment by kingthorin** [comment]
Unit tests added.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank!

**Pull request merged**
