### PR TITLE
Use Maven Central only

### PR DESCRIPTION
**Pull request by thc202**
Remove usage of JCenter, which will be retired.

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]

**Comment by kingthorin** [comment]
I'm trusting that specifying these two prevents the other from being used 😀 Because I don't see any removal.

**Comment by thc202** [comment]
Right, JCenter was being used by default, declaring those will stop using the former.

**Comment by ricekot** [comment]
that seems to be the case: https://docs.gradle.org/current/userguide/declaring_repositories.html#strict_limitation_to_declared_repositories

**Review by ricekot — APPROVED** [review]
Thank you!

**Review by psiinon — APPROVED** [review]

**Pull request merged**
