### PR TITLE
chore: pscanrules: Update cache-control details to be more lenient

### PR DESCRIPTION
**Pull request by kingthorin**
- CHANGELOG > Added change note.
- Messages.properties > Update name, description, and solution to be more lenient.

Fixes zaproxy/zaproxy#6462

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Comment by kingthorin** [comment]
Should we also reduce risk low ➡️ info?

**Comment by thc202** [comment]
That sounds good.

**Comment by kingthorin** [comment]
Okay, I've tweaked that as well.

**Review by psiinon — APPROVED** [review]

**Pull request merged**
