### PR TITLE
Tidy up loggers

### PR DESCRIPTION
**Pull request by thc202**
Make them private, static, and final.
Normalise the name, use `LOGGER`.
Remove a commented out loggers.
Update changelogs where needed.

### CODE REVIEW

**Review by kingthorin — COMMENTED** [review]
Worth naming as constants?

**Comment by thc202** [comment]
I didn't want to do too many changes, there are others (than the ones being changed) that are not using the expected case, can rename them as well in this PR but will do that for all not just the ones being changed.
We just need to decide `LOG` vs `LOGGER`then, I prefer the latter.

**Comment by kingthorin** [comment]
If you agree it’s worth doing then I’m good with it being done in this PR and I agree with `LOGGER`.

**Comment by psiinon** [comment]
I have no real preference between `LOG` and `LOGGER` - and agree that consistency is always good 😄

**Comment by psiinon** [comment]
I thought we were waiting for you to change to use LOG or LOGGER? 😉

**Comment by kingthorin** [comment]
Sorry I shoulda been more specific, I was poking @thc202 as it’s his PR 😇

**Comment by kingthorin** [comment]
@thc202 want me to tackle the naming?

**Comment by thc202** [comment]
I will finish this week.

**Comment by kingthorin** [comment]
Ok, thanks.

**Comment by kingthorin** [comment]
Thanks, will skim it sometime today.

**Comment by thc202** [comment]
For the record I didn't change the regular expression CodeQL is alerting to.

**Comment by thc202** [comment]
Will address the conflicts soon.

**Review by kingthorin — APPROVED** [review]

**Comment by kingthorin** [comment]
Still LGTM

**Review by psiinon — APPROVED** [review]

**Pull request merged**
