### PR TITLE
Network: Update user agents

### PR DESCRIPTION
**Pull request by psiinon**
## Overview
As per title

## Related Issues
https://github.com/zaproxy/zaproxy/issues/8706

## Checklist
- [ ] Update help
- [x] Update changelog
- [x] Run `./gradlew spotlessApply` for code formatting
- [ ] Write tests
- [ ] Check code coverage
- [x] Sign-off commits
- [x] Squash commits
- [x] Use a descriptive title

For more details, please refer to the [developer rules and guidelines](https://www.zaproxy.org/docs/developer/dev-rules-and-guidelines/).

### CODE REVIEW

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Comment by kingthorin** [comment]
Test needs to be tweaked

**Comment by psiinon** [comment]
Logo
**Checkmarx One – Scan Summary & Details** – [5a38fef0\-10cf\-4479\-a9d4\-aa76033c0d82](https://eu.ast.checkmarx.net/projects/0da811fa-6373-42b1-bbb6-d0026285b136/scans?id=5a38fef0-10cf-4479-a9d4-aa76033c0d82&branch=psiinon%2Fntwwork%2F2.16-ua)
### No New Or Fixed Issues Found

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Review by kingthorin — APPROVED** [review]

**Pull request merged**
