### PR TITLE
Ajax Spider - generate start and stop events

### PR DESCRIPTION
**Pull request by psiinon**
Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Comment by psiinon** [comment]
Arg, forgot spotlessApply - now done

**Comment by kingthorin** [comment]
Is there advantage or logic to doing the event handling within the `notifyListenersSpiderStarted` `notifyListenersSpiderStopped` methods? They're currently private and seem to only be called once, but would that be more future friendly? (Food for thought.)

**Comment by psiinon** [comment]
I dont think those methods are ones that someone should need to call from outside of the add-on, and therefore if we need to call them from somewhere else in the same add-on then we can just make them public when required. But dont really feel strongly about it eather way...

**Comment by kingthorin** [comment]
Okay, let's leave it as is.

**Pull request merged**
