### PR TITLE
Updated ImportURL add-on to use new Import Menu

### PR DESCRIPTION
**Pull request by Yashvendra**
Part of issue [zaproxy#3578](https://github.com/zaproxy/zaproxy/issues/3578)

### CODE REVIEW

**Comment by thc202** [comment]
Changed to WIP, we can't merge until we have the new core jar available here.

**Comment by thc202** [comment]
The `ZapAddOn.xml` should mention the change done though.

**Comment by thc202** [comment]
The help of the add-on needs to be updated to mention the new menu.

**Comment by thc202** [comment]
The pull request is now targeting master branch (after zap-extensions beta branch merge, zaproxy/zaproxy#5302).

**Comment by psiinon** [comment]
This pull request **introduces 4 alerts** when merging d4d041766b0399e562ae6873f680bc7f13bdfcb4 into e85eb86d6e5490a850b184d00caf809cb6614d79 - [view on LGTM.com](https://lgtm.com/projects/g/zaproxy/zap-extensions/rev/pr-db8d8d02f8336d59ceec600a3d3375cb3d1a85d4)

**new alerts:**

* 3 for Unused variable, import, function or class
* 1 for Comparison between inconvertible types

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by thc202** [comment]
Updated with ZAP 2.8.0.

**Comment by kingthorin** [comment]
Does this need to be rebased? (I thought we had fixed the download issues...)

https://travis-ci.com/zaproxy/zap-extensions/jobs/207172099#L3648
```log
> Task :addOns:webdrivers:webdriverlinux:downloadChromeDriver FAILED
There was an error managing chromedriver 75.0.3770.8 (Inflater has been closed)
java.lang.NullPointerException: Inflater has been closed
	at java.util.zip.Inflater.ensureOpen(Inflater.java:389)
	at java.util.zip.Inflater.inflate(Inflater.java:257)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:152)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at java.util.Properties$LineReader.readLine(Properties.java:435)
	at java.util.Properties.load0(Properties.java:353)
	at java.util.Properties.load(Properties.java:341)
	at io.github.bonigarcia.wdm.Config.getPropertyFrom(Config.java:227)
	at io.github.bonigarcia.wdm.Config.getProperty(Config.java:205)
	at io.github.bonigarcia.wdm.Config.resolver(Config.java:173)
	at io.github.bonigarcia.wdm.Config.resolve(Config.java:160)
	at io.github.bonigarcia.wdm.Config.getTargetPath(Config.java:284)
	at io.github.bonigarcia.wdm.Downloader.getTargetPath(Downloader.java:115)
	at io.github.bonigarcia.wdm.WebDriverManager.getFilesInCache(WebDriverManager.java:827)
	at io.github.bonigarcia.wdm.WebDriverManager.getDriverFromCache(WebDriverManager.java:782)
	at io.github.bonigarcia.wdm.WebDriverManager.handleCache(WebDriverManager.java:773)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:495)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:251)
	at org.zaproxy.gradle.tasks.DownloadWebDriver$Download.run(DownloadWebDriver.java:155)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:39)
	at org.gradle.workers.internal.IsolatedClassloaderWorkerFactory$WorkerCallable.call(IsolatedClassloaderWorkerFactory.java:165)
	at org.gradle.workers.internal.IsolatedClassloaderWorkerFactory.executeInWorkerClassLoader(IsolatedClassloaderWorkerFactory.java:93)
	at org.gradle.workers.internal.IsolatedClassloaderWorkerFactory.access$000(IsolatedClassloaderWorkerFactory.java:53)
	at org.gradle.workers.internal.IsolatedClassloaderWorkerFactory$1$1.execute(IsolatedClassloaderWorkerFactory.java:72)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.IsolatedClassloaderWorkerFactory$1.execute(IsolatedClassloaderWorkerFactory.java:69)
	at org.gradle.workers.internal.DefaultWorkerExecutor$1.call(DefaultWorkerExecutor.java:105)
	at org.gradle.workers.internal.DefaultWorkerExecutor$1.call(DefaultWorkerExecutor.java:99)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
> Task :addOns:jxbrowsers:jxbrowserwindows64:generateZapAddOnManifest
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':addOns:webdrivers:webdriverlinux:downloadChromeDriver'.
> A failure occurred while executing org.zaproxy.gradle.tasks.DownloadWebDriver$Download
   > java.lang.NullPointerException: Inflater has been closed
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 20m 31s
```

**Comment by thc202** [comment]
It already is, that's probably a transient failure, restarted the build.

**Pull request merged**
