### PR TITLE
Automation: added method for setting exit value

### PR DESCRIPTION
**Pull request by psiinon**
## Overview
As per title.

I've not updated the help as I think the logical place to document this is here: https://www.zaproxy.org/docs/automate/automation-framework/#exit-value

## Checklist
- [ ] Update help
- [x] Update changelog
- [x] Run `./gradlew spotlessApply` for code formatting
- [ ] Write tests
- [x] Check code coverage
- [x] Sign-off commits
- [x] Squash commits
- [x] Use a descriptive title

For more details, please refer to the [developer rules and guidelines](https://www.zaproxy.org/docs/developer/dev-rules-and-guidelines/).

### CODE REVIEW

**Review by kingthorin — COMMENTED** [review]
Add an example script to the help?

**Comment by psiinon** [comment]
> Add an example script to the help?

Read my first comment 😁

**Comment by kingthorin** [comment]
🤦‍♂️

**Review by kingthorin — APPROVED** [review]

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Comment by psiinon** [comment]
Logo
**Checkmarx One – Scan Summary & Details** – [7e8b5874\-93e4\-4cc6\-8865\-eef242bb52b0](https://eu.ast.checkmarx.net/projects/0da811fa-6373-42b1-bbb6-d0026285b136/scans?id=7e8b5874-93e4-4cc6-8865-eef242bb52b0&branch=psiinon%2Fauto%2Fset-exit)
### No New Or Fixed Issues Found

**Pull request merged**
