### PR TITLE
reports: replace vars in reportDir and reportFile

### PR DESCRIPTION
**Pull request by thc202**
Replace variables present in `reportDir` and `reportFile` when running
the automation job.

### CODE REVIEW

**Comment by thc202** [comment]
@kingthorin could you checkout this branch and run the tests on Windows? Not sure if the path separator used in the assertions will cause problems.

**Comment by kingthorin** [comment]
Sure

**Comment by kingthorin** [comment]
Looks like there were Windows issues before this addition:

Eclipse (running all in org.zaproxy.addon.reports.automation):
image

CLI:
```bash
$ ./gradlew :aO:reports:test

> Task :addOns:reports:test

OutputSummaryJobUnitTest > shouldReportInOrderRulesWithAlerts() FAILED
    java.lang.AssertionError at OutputSummaryJobUnitTest.java:322

OutputSummaryJobUnitTest > shouldOutputCorrectShortReport() FAILED
    java.lang.AssertionError at OutputSummaryJobUnitTest.java:521

OutputSummaryJobUnitTest > shouldWarnOnRuleWithAlerts() FAILED
    java.lang.AssertionError at OutputSummaryJobUnitTest.java:152

OutputSummaryJobUnitTest > shouldFailIfConfigOnRuleWithAlerts() FAILED
    java.lang.AssertionError at OutputSummaryJobUnitTest.java:190

OutputSummaryJobUnitTest > shouldIncludeCustomMessage() FAILED
    java.lang.AssertionError at OutputSummaryJobUnitTest.java:654

OutputSummaryJobUnitTest > shouldIgnoreIfConfigOnRuleWithAlerts() FAILED
    java.lang.AssertionError at OutputSummaryJobUnitTest.java:266

OutputSummaryJobUnitTest > shouldInfoIfConfigOnRuleWithAlerts() FAILED
    java.lang.AssertionError at OutputSummaryJobUnitTest.java:228

OutputSummaryJobUnitTest > shouldPassIfNoAlerts() FAILED
    java.lang.AssertionError at OutputSummaryJobUnitTest.java:407

OutputSummaryJobUnitTest > shouldOutputJobsInAlphabeticIdOrder() FAILED
    java.lang.AssertionError at OutputSummaryJobUnitTest.java:438

OutputSummaryJobUnitTest > shouldOutputCorrectLongReport() FAILED
    java.lang.AssertionError at OutputSummaryJobUnitTest.java:478

OutputSummaryJobUnitTest > shouldShowUrlsOnRuleWithAlerts() FAILED
    java.lang.AssertionError at OutputSummaryJobUnitTest.java:375

OutputSummaryJobUnitTest > shouldWarnOnNoURLs() FAILED
    java.lang.AssertionError at OutputSummaryJobUnitTest.java:343

ReportJobUnitTest > shouldReplaceVarInReportFileWhenRunning() FAILED
    java.lang.AssertionError at ReportJobUnitTest.java:226

ReportJobUnitTest > shouldReplaceVarInReportDirWhenRunning() FAILED
    java.lang.AssertionError at ReportJobUnitTest.java:268

88 tests completed, 14 failed

> Task :addOns:reports:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':addOns:reports:test'.
> There were failing tests. See the report at: file:///C:/Users/thorin/Desktop/zap-ws/zap-extensions/addOns/reports/build/reports/tests/test/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s
27 actionable tasks: 7 executed, 20 up-to-date

```

**Comment by kingthorin** [comment]
Maybe use `String fileSeparator = FileSystems.getDefault().getSeparator();` or `char pathSeparatorChar = File.pathSeparatorChar;`

**Comment by thc202** [comment]
Thank you! Are the other failures related to paths?

**Comment by kingthorin** [comment]
All the `OutputSummaryJobUnitTest` failures are related to newlines.

Both of the `ReportJobUnitTest` failures are related to path\separator (like the screenshot earlier).

**Comment by thc202** [comment]
If it's not abusing, could you run all tests in the main branch? (e.g. `./gradlew --continue test`)

**Comment by kingthorin** [comment]
It looks like there are 6 sub-projects which have failures on windows. I'm working on getting the console output written to a file, so that I can cleanup the deprecation warnings and get the details.

**Comment by kingthorin** [comment]
<details>
<summary>Overall failures console output</summary>

```bash
> Task :addOns:kotlin:test

ClassLoaderTests > shouldLoadClassesFromProvidedClassLoader() FAILED
    java.nio.file.InvalidPathException at ClassLoaderTests.java:42

> Task :addOns:scripts:test FAILED

ScriptJobUnitTest > shouldFailToAddIfFileNotReadable() FAILED
    java.lang.AssertionError at ScriptJobUnitTest.java:523

33 tests completed, 1 failed

> Task :addOns:reports:test

OutputSummaryJobUnitTest > shouldReportInOrderRulesWithAlerts() FAILED
    java.lang.AssertionError at OutputSummaryJobUnitTest.java:322

OutputSummaryJobUnitTest > shouldOutputCorrectShortReport() FAILED
    java.lang.AssertionError at OutputSummaryJobUnitTest.java:521

OutputSummaryJobUnitTest > shouldWarnOnRuleWithAlerts() FAILED
    java.lang.AssertionError at OutputSummaryJobUnitTest.java:152

OutputSummaryJobUnitTest > shouldFailIfConfigOnRuleWithAlerts() FAILED
    java.lang.AssertionError at OutputSummaryJobUnitTest.java:190

OutputSummaryJobUnitTest > shouldIncludeCustomMessage() FAILED
    java.lang.AssertionError at OutputSummaryJobUnitTest.java:654

OutputSummaryJobUnitTest > shouldIgnoreIfConfigOnRuleWithAlerts() FAILED
    java.lang.AssertionError at OutputSummaryJobUnitTest.java:266

OutputSummaryJobUnitTest > shouldInfoIfConfigOnRuleWithAlerts() FAILED
    java.lang.AssertionError at OutputSummaryJobUnitTest.java:228

OutputSummaryJobUnitTest > shouldPassIfNoAlerts() FAILED
    java.lang.AssertionError at OutputSummaryJobUnitTest.java:407

OutputSummaryJobUnitTest > shouldOutputJobsInAlphabeticIdOrder() FAILED
    java.lang.AssertionError at OutputSummaryJobUnitTest.java:438

OutputSummaryJobUnitTest > shouldOutputCorrectLongReport() FAILED
    java.lang.AssertionError at OutputSummaryJobUnitTest.java:478

OutputSummaryJobUnitTest > shouldShowUrlsOnRuleWithAlerts() FAILED
    java.lang.AssertionError at OutputSummaryJobUnitTest.java:375

OutputSummaryJobUnitTest > shouldWarnOnNoURLs() FAILED
    java.lang.AssertionError at OutputSummaryJobUnitTest.java:343

> Task :addOns:automation:test
> Task :addOns:ascanrulesBeta:test
> Task :addOns:network:test

> Task :addOns:reports:test FAILED

82 tests completed, 12 failed

> Task :addOns:automation:test

ContextWrapperUnitTest > shouldParseScriptSessionMgmtInNewFormat() FAILED
    java.lang.AssertionError at ContextWrapperUnitTest.java:327

ContextWrapperUnitTest > shouldParseScriptSessionMgmtInOldFormat() FAILED
    java.lang.AssertionError at ContextWrapperUnitTest.java:274

> Task :addOns:kotlin:test FAILED

3 tests completed, 1 failed

> Task :addOns:network:test

ExtensionNetworkUnitTest > shouldWriteRootCaCertAsPem() FAILED
    java.lang.AssertionError at ExtensionNetworkUnitTest.java:726

NetworkApiUnitTest > shouldThrowApiExceptionIfUnableToListenForAddedLocalServer() FAILED
    org.opentest4j.AssertionFailedError at NetworkApiUnitTest.java:771

NetworkApiUnitTest > shouldReturnPemForExistingRootCaCert() FAILED
    java.lang.AssertionError at NetworkApiUnitTest.java:341

CertificateUtilsUnitTest > shouldConvertKeyStoreToCertificatePemFile() FAILED
    java.lang.AssertionError at CertificateUtilsUnitTest.java:416

CertificateUtilsUnitTest > shouldConvertKeyStoreToCertificatePemString() FAILED
    java.lang.AssertionError at CertificateUtilsUnitTest.java:381

779 tests completed, 5 failed, 2 skipped

> Task :addOns:network:test FAILED

> Task :addOns:automation:test FAILED

332 tests completed, 2 failed, 1 skipped

FAILURE: Build completed with 5 failures.
```

</details>

kotlin
```bash
shouldLoadClassesFromProvidedClassLoader()

java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/thorin/Desktop/zap-ws/zap-extensions/addOns/kotlin/build/resources/test/org/zaproxy/addon/kotlin/testclasspath
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at org.zaproxy.addon.kotlin.ClassLoaderTests.testFallbackClassLoader(ClassLoaderTests.java:42)
	at org.zaproxy.addon.kotlin.ClassLoaderTests.shouldLoadClassesFromProvidedClassLoader(ClassLoaderTests.java:59)
```

Scripts
```bash
shouldFailToAddIfFileNotReadable()

java.lang.AssertionError: 
Expected: is <true>
     but: was <false>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.zaproxy.zap.extension.scripts.automation.ScriptJobUnitTest.shouldFailToAddIfFileNotReadable(ScriptJobUnitTest.java:523)
```

Reports (there are a number but all similar to the following [LF vs CRLF]):
```bash
java.lang.AssertionError: 
Expected: is "Total of 3 URLs\nFAIL-NEW: rule1 [1] x 3 \nFAIL-NEW: 1\tFAIL-INPROG: 0\tWARN-NEW: 0\tWARN-INPROG: 0\tINFO: 0\tIGNORE: 0\tPASS: 0\n"
     but: was "Total of 3 URLs\r\nFAIL-NEW: rule1 [1] x 3 \r\nFAIL-NEW: 1\tFAIL-INPROG: 0\tWARN-NEW: 0\tWARN-INPROG: 0\tINFO: 0\tIGNORE: 0\tPASS: 0\r\n"
```

automation
```bash
shouldParseScriptSessionMgmtInNewFormat()

java.lang.AssertionError: 
Expected: is <true>
     but: was <false>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.zaproxy.addon.automation.ContextWrapperUnitTest.shouldParseScriptSessionMgmtInNewFormat(ContextWrapperUnitTest.java:327)

shouldParseScriptSessionMgmtInOldFormat()

java.lang.AssertionError: 
Expected: is <true>
     but: was <false>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.zaproxy.addon.automation.ContextWrapperUnitTest.shouldParseScriptSessionMgmtInOldFormat(ContextWrapperUnitTest.java:274)
```

<details>
<summary>network (most of these seem to be CRLF vs LF as well):</summary>

```bash
shouldWriteRootCaCertAsPem()

java.lang.AssertionError: 
Expected: (a string containing "-----BEGIN CERTIFICATE-----" and a string containing "MIIC9TCCAl6gAwIBAgIJANL8E4epRNznMA0GCSqGSIb3DQEBBQUAMFsxGDAWBgNV\n" and a string containing "-----END CERTIFICATE-----" and not a string containing "-----BEGIN PRIVATE KEY-----")
     but: a string containing "MIIC9TCCAl6gAwIBAgIJANL8E4epRNznMA0GCSqGSIb3DQEBBQUAMFsxGDAWBgNV\n" was "-----BEGIN CERTIFICATE-----
MIIC9TCCAl6gAwIBAgIJANL8E4epRNznMA0GCSqGSIb3DQEBBQUAMFsxGDAWBgNV
BAoTD1N1cGVyZmlzaCwgSW5jLjELMAkGA1UEBxMCU0YxCzAJBgNVBAgTAkNBMQsw
CQYDVQQGEwJVUzEYMBYGA1UEAxMPU3VwZXJmaXNoLCBJbmMuMB4XDTE0MDUxMjE2
MjUyNloXDTM0MDUwNzE2MjUyNlowWzEYMBYGA1UEChMPU3VwZXJmaXNoLCBJbmMu
MQswCQYDVQQHEwJTRjELMAkGA1UECBMCQ0ExCzAJBgNVBAYTAlVTMRgwFgYDVQQD
Ew9TdXBlcmZpc2gsIEluYy4wgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAOjz
Shh2Xxk/sc9Y6X9DBwmVgDXFD/5xMSeBmRImIKXfj2r8QlU57gk4idngNsSsAYJb
1Tnm+Y8HiN/+7vahFM6pdEXY/fAXVyqC4XouEpNarIrXFWPRt5tVgA9YvBxJ7SBi
3bZMpTrrHD2g/3pxptMQeDOuS8Ic/ZJKocPnQaQtAgMBAAGjgcAwgb0wDAYDVR0T
BAUwAwEB/zAdBgNVHQ4EFgQU+5izU38URC7o7tUJml4OVoaoNYgwgY0GA1UdIwSB
hTCBgoAU+5izU38URC7o7tUJml4OVoaoNYihX6RdMFsxGDAWBgNVBAoTD1N1cGVy
ZmlzaCwgSW5jLjELMAkGA1UEBxMCU0YxCzAJBgNVBAgTAkNBMQswCQYDVQQGEwJV
UzEYMBYGA1UEAxMPU3VwZXJmaXNoLCBJbmMuggkA0vwTh6lE3OcwDQYJKoZIhvcN
AQEFBQADgYEApHyg7ApKx3DEcWjzOyLi3JyN0JL+c35yK1VEmxu0Qusfr76645Oj
1IsYwpTws6a9ZTRMzST4GQvFFQra81eLqYbPbMPuhC+FCxkUF5i0DNSWi+kczJXJ
TtCqSwGl9t9JEoFqvtW+znZ9TqyLiOMw7TGEUI+88VAqW0qmXnwPcfo=
-----END CERTIFICATE-----
"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.zaproxy.addon.network.ExtensionNetworkUnitTest.shouldWriteRootCaCertAsPem(ExtensionNetworkUnitTest.java:726)

shouldReturnPemForExistingRootCaCert()

java.lang.AssertionError: 
Expected: (a string containing "-----BEGIN CERTIFICATE-----" and a string containing "MIIC9TCCAl6gAwIBAgIJANL8E4epRNznMA0GCSqGSIb3DQEBBQUAMFsxGDAWBgNV\n" and a string containing "-----END CERTIFICATE-----" and not a string containing "-----BEGIN PRIVATE KEY-----")
     but: a string containing "MIIC9TCCAl6gAwIBAgIJANL8E4epRNznMA0GCSqGSIb3DQEBBQUAMFsxGDAWBgNV\n" was "-----BEGIN CERTIFICATE-----
MIIC9TCCAl6gAwIBAgIJANL8E4epRNznMA0GCSqGSIb3DQEBBQUAMFsxGDAWBgNV
BAoTD1N1cGVyZmlzaCwgSW5jLjELMAkGA1UEBxMCU0YxCzAJBgNVBAgTAkNBMQsw
CQYDVQQGEwJVUzEYMBYGA1UEAxMPU3VwZXJmaXNoLCBJbmMuMB4XDTE0MDUxMjE2
MjUyNloXDTM0MDUwNzE2MjUyNlowWzEYMBYGA1UEChMPU3VwZXJmaXNoLCBJbmMu
MQswCQYDVQQHEwJTRjELMAkGA1UECBMCQ0ExCzAJBgNVBAYTAlVTMRgwFgYDVQQD
Ew9TdXBlcmZpc2gsIEluYy4wgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAOjz
Shh2Xxk/sc9Y6X9DBwmVgDXFD/5xMSeBmRImIKXfj2r8QlU57gk4idngNsSsAYJb
1Tnm+Y8HiN/+7vahFM6pdEXY/fAXVyqC4XouEpNarIrXFWPRt5tVgA9YvBxJ7SBi
3bZMpTrrHD2g/3pxptMQeDOuS8Ic/ZJKocPnQaQtAgMBAAGjgcAwgb0wDAYDVR0T
BAUwAwEB/zAdBgNVHQ4EFgQU+5izU38URC7o7tUJml4OVoaoNYgwgY0GA1UdIwSB
hTCBgoAU+5izU38URC7o7tUJml4OVoaoNYihX6RdMFsxGDAWBgNVBAoTD1N1cGVy
ZmlzaCwgSW5jLjELMAkGA1UEBxMCU0YxCzAJBgNVBAgTAkNBMQswCQYDVQQGEwJV
UzEYMBYGA1UEAxMPU3VwZXJmaXNoLCBJbmMuggkA0vwTh6lE3OcwDQYJKoZIhvcN
AQEFBQADgYEApHyg7ApKx3DEcWjzOyLi3JyN0JL+c35yK1VEmxu0Qusfr76645Oj
1IsYwpTws6a9ZTRMzST4GQvFFQra81eLqYbPbMPuhC+FCxkUF5i0DNSWi+kczJXJ
TtCqSwGl9t9JEoFqvtW+znZ9TqyLiOMw7TGEUI+88VAqW0qmXnwPcfo=
-----END CERTIFICATE-----
"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.zaproxy.addon.network.NetworkApiUnitTest.shouldReturnPemForExistingRootCaCert(NetworkApiUnitTest.java:341)

shouldThrowApiExceptionIfUnableToListenForAddedLocalServer()

org.opentest4j.AssertionFailedError: Expected org.zaproxy.zap.extension.api.ApiException to be thrown, but nothing was thrown.
	at app//org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:71)
	at app//org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:37)
	at app//org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3082)
	at app//org.zaproxy.addon.network.NetworkApiUnitTest.shouldThrowApiExceptionIfUnableToListenForAddedLocalServer(NetworkApiUnitTest.java:771)

shouldConvertKeyStoreToCertificatePemFile()

java.lang.AssertionError: 
Expected: is "-----BEGIN CERTIFICATE-----\nMIIC9TCCAl6gAwIBAgIJANL8E4epRNznMA0GCSqGSIb3DQEBBQUAMFsxGDAWBgNV\nBAoTD1N1cGVyZmlzaCwgSW5jLjELMAkGA1UEBxMCU0YxCzAJBgNVBAgTAkNBMQsw\nCQYDVQQGEwJVUzEYMBYGA1UEAxMPU3VwZXJmaXNoLCBJbmMuMB4XDTE0MDUxMjE2\nMjUyNloXDTM0MDUwNzE2MjUyNlowWzEYMBYGA1UEChMPU3VwZXJmaXNoLCBJbmMu\nMQswCQYDVQQHEwJTRjELMAkGA1UECBMCQ0ExCzAJBgNVBAYTAlVTMRgwFgYDVQQD\nEw9TdXBlcmZpc2gsIEluYy4wgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAOjz\nShh2Xxk/sc9Y6X9DBwmVgDXFD/5xMSeBmRImIKXfj2r8QlU57gk4idngNsSsAYJb\n1Tnm+Y8HiN/+7vahFM6pdEXY/fAXVyqC4XouEpNarIrXFWPRt5tVgA9YvBxJ7SBi\n3bZMpTrrHD2g/3pxptMQeDOuS8Ic/ZJKocPnQaQtAgMBAAGjgcAwgb0wDAYDVR0T\nBAUwAwEB/zAdBgNVHQ4EFgQU+5izU38URC7o7tUJml4OVoaoNYgwgY0GA1UdIwSB\nhTCBgoAU+5izU38URC7o7tUJml4OVoaoNYihX6RdMFsxGDAWBgNVBAoTD1N1cGVy\nZmlzaCwgSW5jLjELMAkGA1UEBxMCU0YxCzAJBgNVBAgTAkNBMQswCQYDVQQGEwJV\nUzEYMBYGA1UEAxMPU3VwZXJmaXNoLCBJbmMuggkA0vwTh6lE3OcwDQYJKoZIhvcN\nAQEFBQADgYEApHyg7ApKx3DEcWjzOyLi3JyN0JL+c35yK1VEmxu0Qusfr76645Oj\n1IsYwpTws6a9ZTRMzST4GQvFFQra81eLqYbPbMPuhC+FCxkUF5i0DNSWi+kczJXJ\nTtCqSwGl9t9JEoFqvtW+znZ9TqyLiOMw7TGEUI+88VAqW0qmXnwPcfo=\n-----END CERTIFICATE-----\n"
     but: was "-----BEGIN CERTIFICATE-----\r\nMIIC9TCCAl6gAwIBAgIJANL8E4epRNznMA0GCSqGSIb3DQEBBQUAMFsxGDAWBgNV\r\nBAoTD1N1cGVyZmlzaCwgSW5jLjELMAkGA1UEBxMCU0YxCzAJBgNVBAgTAkNBMQsw\r\nCQYDVQQGEwJVUzEYMBYGA1UEAxMPU3VwZXJmaXNoLCBJbmMuMB4XDTE0MDUxMjE2\r\nMjUyNloXDTM0MDUwNzE2MjUyNlowWzEYMBYGA1UEChMPU3VwZXJmaXNoLCBJbmMu\r\nMQswCQYDVQQHEwJTRjELMAkGA1UECBMCQ0ExCzAJBgNVBAYTAlVTMRgwFgYDVQQD\r\nEw9TdXBlcmZpc2gsIEluYy4wgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAOjz\r\nShh2Xxk/sc9Y6X9DBwmVgDXFD/5xMSeBmRImIKXfj2r8QlU57gk4idngNsSsAYJb\r\n1Tnm+Y8HiN/+7vahFM6pdEXY/fAXVyqC4XouEpNarIrXFWPRt5tVgA9YvBxJ7SBi\r\n3bZMpTrrHD2g/3pxptMQeDOuS8Ic/ZJKocPnQaQtAgMBAAGjgcAwgb0wDAYDVR0T\r\nBAUwAwEB/zAdBgNVHQ4EFgQU+5izU38URC7o7tUJml4OVoaoNYgwgY0GA1UdIwSB\r\nhTCBgoAU+5izU38URC7o7tUJml4OVoaoNYihX6RdMFsxGDAWBgNVBAoTD1N1cGVy\r\nZmlzaCwgSW5jLjELMAkGA1UEBxMCU0YxCzAJBgNVBAgTAkNBMQswCQYDVQQGEwJV\r\nUzEYMBYGA1UEAxMPU3VwZXJmaXNoLCBJbmMuggkA0vwTh6lE3OcwDQYJKoZIhvcN\r\nAQEFBQADgYEApHyg7ApKx3DEcWjzOyLi3JyN0JL+c35yK1VEmxu0Qusfr76645Oj\r\n1IsYwpTws6a9ZTRMzST4GQvFFQra81eLqYbPbMPuhC+FCxkUF5i0DNSWi+kczJXJ\r\nTtCqSwGl9t9JEoFqvtW+znZ9TqyLiOMw7TGEUI+88VAqW0qmXnwPcfo=\r\n-----END CERTIFICATE-----\r\n"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.zaproxy.addon.network.internal.cert.CertificateUtilsUnitTest.shouldConvertKeyStoreToCertificatePemFile(CertificateUtilsUnitTest.java:416)

shouldConvertKeyStoreToCertificatePemString()

java.lang.AssertionError: 
Expected: is "-----BEGIN CERTIFICATE-----\nMIIC9TCCAl6gAwIBAgIJANL8E4epRNznMA0GCSqGSIb3DQEBBQUAMFsxGDAWBgNV\nBAoTD1N1cGVyZmlzaCwgSW5jLjELMAkGA1UEBxMCU0YxCzAJBgNVBAgTAkNBMQsw\nCQYDVQQGEwJVUzEYMBYGA1UEAxMPU3VwZXJmaXNoLCBJbmMuMB4XDTE0MDUxMjE2\nMjUyNloXDTM0MDUwNzE2MjUyNlowWzEYMBYGA1UEChMPU3VwZXJmaXNoLCBJbmMu\nMQswCQYDVQQHEwJTRjELMAkGA1UECBMCQ0ExCzAJBgNVBAYTAlVTMRgwFgYDVQQD\nEw9TdXBlcmZpc2gsIEluYy4wgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAOjz\nShh2Xxk/sc9Y6X9DBwmVgDXFD/5xMSeBmRImIKXfj2r8QlU57gk4idngNsSsAYJb\n1Tnm+Y8HiN/+7vahFM6pdEXY/fAXVyqC4XouEpNarIrXFWPRt5tVgA9YvBxJ7SBi\n3bZMpTrrHD2g/3pxptMQeDOuS8Ic/ZJKocPnQaQtAgMBAAGjgcAwgb0wDAYDVR0T\nBAUwAwEB/zAdBgNVHQ4EFgQU+5izU38URC7o7tUJml4OVoaoNYgwgY0GA1UdIwSB\nhTCBgoAU+5izU38URC7o7tUJml4OVoaoNYihX6RdMFsxGDAWBgNVBAoTD1N1cGVy\nZmlzaCwgSW5jLjELMAkGA1UEBxMCU0YxCzAJBgNVBAgTAkNBMQswCQYDVQQGEwJV\nUzEYMBYGA1UEAxMPU3VwZXJmaXNoLCBJbmMuggkA0vwTh6lE3OcwDQYJKoZIhvcN\nAQEFBQADgYEApHyg7ApKx3DEcWjzOyLi3JyN0JL+c35yK1VEmxu0Qusfr76645Oj\n1IsYwpTws6a9ZTRMzST4GQvFFQra81eLqYbPbMPuhC+FCxkUF5i0DNSWi+kczJXJ\nTtCqSwGl9t9JEoFqvtW+znZ9TqyLiOMw7TGEUI+88VAqW0qmXnwPcfo=\n-----END CERTIFICATE-----\n"
     but: was "-----BEGIN CERTIFICATE-----\r\nMIIC9TCCAl6gAwIBAgIJANL8E4epRNznMA0GCSqGSIb3DQEBBQUAMFsxGDAWBgNV\r\nBAoTD1N1cGVyZmlzaCwgSW5jLjELMAkGA1UEBxMCU0YxCzAJBgNVBAgTAkNBMQsw\r\nCQYDVQQGEwJVUzEYMBYGA1UEAxMPU3VwZXJmaXNoLCBJbmMuMB4XDTE0MDUxMjE2\r\nMjUyNloXDTM0MDUwNzE2MjUyNlowWzEYMBYGA1UEChMPU3VwZXJmaXNoLCBJbmMu\r\nMQswCQYDVQQHEwJTRjELMAkGA1UECBMCQ0ExCzAJBgNVBAYTAlVTMRgwFgYDVQQD\r\nEw9TdXBlcmZpc2gsIEluYy4wgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAOjz\r\nShh2Xxk/sc9Y6X9DBwmVgDXFD/5xMSeBmRImIKXfj2r8QlU57gk4idngNsSsAYJb\r\n1Tnm+Y8HiN/+7vahFM6pdEXY/fAXVyqC4XouEpNarIrXFWPRt5tVgA9YvBxJ7SBi\r\n3bZMpTrrHD2g/3pxptMQeDOuS8Ic/ZJKocPnQaQtAgMBAAGjgcAwgb0wDAYDVR0T\r\nBAUwAwEB/zAdBgNVHQ4EFgQU+5izU38URC7o7tUJml4OVoaoNYgwgY0GA1UdIwSB\r\nhTCBgoAU+5izU38URC7o7tUJml4OVoaoNYihX6RdMFsxGDAWBgNVBAoTD1N1cGVy\r\nZmlzaCwgSW5jLjELMAkGA1UEBxMCU0YxCzAJBgNVBAgTAkNBMQswCQYDVQQGEwJV\r\nUzEYMBYGA1UEAxMPU3VwZXJmaXNoLCBJbmMuggkA0vwTh6lE3OcwDQYJKoZIhvcN\r\nAQEFBQADgYEApHyg7ApKx3DEcWjzOyLi3JyN0JL+c35yK1VEmxu0Qusfr76645Oj\r\n1IsYwpTws6a9ZTRMzST4GQvFFQra81eLqYbPbMPuhC+FCxkUF5i0DNSWi+kczJXJ\r\nTtCqSwGl9t9JEoFqvtW+znZ9TqyLiOMw7TGEUI+88VAqW0qmXnwPcfo=\r\n-----END CERTIFICATE-----\r\n"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.zaproxy.addon.network.internal.cert.CertificateUtilsUnitTest.shouldConvertKeyStoreToCertificatePemString(CertificateUtilsUnitTest.java:381)
```

</details>

**Comment by kingthorin** [comment]
While it isn't clear from the output above I can confirm that the automation failure is due to a path issue. It currently uses:
`.contains("/sessmgmt-newformat"),` in one of the assertions if the slash is dropped the test is fine. (It would likely also be fine if the proper path separator was used/appended.)

**Review by kingthorin — APPROVED** [review]

**Review by psiinon — APPROVED** [review]

**Pull request merged**
