### PR TITLE
web-backdoors file removed

### PR DESCRIPTION
**Pull request by svkrdj**
Web Backdoors folder removed (successfully build).

### CODE REVIEW

**Comment by svkrdj** [comment]
I think I have messed up my branches. The first 4 commits are by mistake and I am trying to resolve that :disappointed: . And please provide the feedback on the PR.

**Comment by kingthorin** [comment]
Other than the extra commits it looks ok to me. You should add a change to the unreleased section of CHANGELOG.md

Since this is a simple change (mostly a removal) to resolve your commit issue(s) you could: switch to master, fetch/merge (from upstream [zaproxy/zap-extensions]), delete the local "split-fuzzdb" branch, create a new (up-to-date) "split-fuzzdb" branch, do the removals and CHANGELOG.md update then force push back to origin (which will update this PR since your local branch will be the same name as this remote [origin] branch).

**Comment by svkrdj** [comment]
Thanks for the time. On my way

**Comment by thc202** [comment]
Thanks!

**Pull request merged**
