### PR TITLE
postman: Add dialogs for importing through the UI

### PR DESCRIPTION
**Pull request by VitikaSoni**
Part of https://github.com/zaproxy/zaproxy/issues/6960

Signed-off-by: VitikaSoni <vitika.program@gmail.com>

### CODE REVIEW

**Comment by thc202** [comment]
Would be great to retain the values in the dialogues (like #2916), as that improves the usability.

**Comment by thc202** [comment]
The menus could be mentioned in the help.

**Comment by VitikaSoni** [comment]
This is ready for review

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Review by psiinon — APPROVED** [review]

**Pull request merged**
