### PR TITLE
Double check potential SQL timing issues

### PR DESCRIPTION
**Pull request by psiinon**
Plan to change all similar rules like this.

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
Could we also ensure the re-check is done single threaded?

**Comment by psiinon** [comment]
Do we really want to do that? I think we want to do the test while the system is still under load as its a safe check. The alternative is trying the attack again when the system in not underload but we dont have the infrastructure to do that right now.

**Comment by kingthorin** [comment]
I’m good with either, it was just a thought.

**Comment by psiinon** [comment]
Ready for review but I still need to run manually against some test sites...

**Comment by psiinon** [comment]
Just confirmed that a known FP vs a custom app is fixed by these changes.
I've also run the rules vs wavsep - it finds 102 SQLi issues vs 104 with the previous rules, which I'm ok with.
So this should be ready for review now.

**Comment by kingthorin** [comment]
One of the unittests failed in Java 11?

**Comment by psiinon** [comment]
Its failing as for some reason its making 28 reqs on java 11 vs 24 or fewer on java 8 :/
Not sure why, but in any case maybe those limits are a bit too strict?

**Comment by psiinon** [comment]
Ok, finally passed so ready for review

**Review by thc202 — APPROVED** [review]

**Pull request merged**
