### PR TITLE
fix: RequestMethod typo

### PR DESCRIPTION
**Pull request by naggingant**
Fixes https://github.com/zaproxy/zaproxy/issues/6666

### CODE REVIEW

**Comment by psiinon** [comment]
Thanks @naggingant - can you sign off your commit as per https://github.com/zaproxy/zap-extensions/pull/3023/checks?check_run_id=2989401706

**Comment by kingthorin** [comment]
To address the DCO requirement you'll need to sign-off the commit(s):

- https://github.com/zaproxy/zaproxy/blob/develop/CONTRIBUTING.md#developer-certificate-of-origin
- https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff

---

The changelog should also be updated.

**Comment by thc202** [comment]
There should be a test verifying the fix.

**Comment by naggingant** [comment]
Apologies for the newbie mistakes, and thanks for the guidance :man_facepalming: I can hopefully get back to this tomorrow

**Comment by kingthorin** [comment]
No problem, thanks for tackling it!

**Comment by naggingant** [comment]
Hi, I resolved your comments, thanks again. Hope it makes sense!

**Comment by thc202** [comment]
I'd suggest something like:
```diff
diff --git a/addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/network/RequestorUnitTest.java b/addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/network/RequestorUnitTest.java
index b4f5b1fe5..ce83c3b9c 100644
--- a/addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/network/RequestorUnitTest.java
+++ b/addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/network/RequestorUnitTest.java
@@ -23,7 +23,9 @@ import static fi.iki.elonen.NanoHTTPD.newFixedLengthResponse;
 import static org.hamcrest.MatcherAssert.assertThat;
 import static org.hamcrest.Matchers.empty;
 import static org.hamcrest.Matchers.equalTo;
+import static org.hamcrest.Matchers.hasSize;
 import static org.hamcrest.Matchers.is;
+import static org.junit.jupiter.params.provider.Arguments.arguments;
 
 import fi.iki.elonen.NanoHTTPD;
 import fi.iki.elonen.NanoHTTPD.IHTTPSession;
@@ -33,7 +35,11 @@ import java.util.ArrayList;
 import java.util.Arrays;
 import java.util.Collections;
 import java.util.List;
+import java.util.stream.Stream;
 import org.junit.jupiter.api.Test;
+import org.junit.jupiter.params.ParameterizedTest;
+import org.junit.jupiter.params.provider.Arguments;
+import org.junit.jupiter.params.provider.MethodSource;
 import org.parosproxy.paros.network.HttpSender;
 import org.zaproxy.zap.extension.openapi.AbstractServerTest;
 import org.zaproxy.zap.testutils.NanoServerHandler;
@@ -41,6 +47,43 @@ import org.zaproxy.zap.testutils.NanoServerHandler;
 /** Unit test for {@link Requestor}. */
 class RequestorUnitTest extends AbstractServerTest {
 
+    static Stream<Arguments> requestMethods() {
+        return Stream.of(
+                arguments(RequestMethod.GET, "GET"),
+                arguments(RequestMethod.POST, "POST"),
+                arguments(RequestMethod.PUT, "PUT"),
+                arguments(RequestMethod.OPTIONS, "OPTIONS"),
+                arguments(RequestMethod.HEAD, "HEAD"),
+                arguments(RequestMethod.DELETE, "DELETE"),
+                arguments(RequestMethod.PATCH, "PATCH"));
+    }
+
+    @ParameterizedTest
+    @MethodSource("requestMethods")
+    void shouldUseCorrectRequestMethod(RequestMethod method, String expectedMethod) {
+        // Given
+        String baseUrl = "http://localhost:" + nano.getListeningPort() + "/";
+        this.nano.addHandler(
+                new NanoServerHandler("/") {
+                    @Override
+                    protected Response serve(IHTTPSession session) {
+                        return newFixedLengthResponse("");
+                    }
+                });
+
+        List<String> requestedMethod = new ArrayList<>();
+        Requestor requestor = new Requestor(HttpSender.MANUAL_REQUEST_INITIATOR);
+        RequesterListener listener =
+                (msg, initiator) -> requestedMethod.add(msg.getRequestHeader().getMethod());
+        requestor.addListener(listener);
+        // When
+        List<String> errors = requestor.run(Arrays.asList(requestModel(method, baseUrl)));
+        // Then
+        assertThat(errors, is(empty()));
+        assertThat(requestedMethod, hasSize(1));
+        assertThat(requestedMethod.get(0), is(equalTo(expectedMethod)));
+    }
+
     @Test
     void shouldNotifyAllRedirectsFollowed() {
         // Given
@@ -76,7 +119,8 @@ class RequestorUnitTest extends AbstractServerTest {
                                         + msg.getResponseBody().toString());
         requestor.addListener(listener);
         // When
-        List<String> errors = requestor.run(Arrays.asList(requestModel("GET", baseUrl)));
+        List<String> errors =
+                requestor.run(Arrays.asList(requestModel(RequestMethod.GET, baseUrl)));
         // Then
         assertThat(errors, is(empty()));
         assertThat(messages.get(0), is(equalTo("GET / Root")));
@@ -85,9 +129,9 @@ class RequestorUnitTest extends AbstractServerTest {
         assertThat(messages.get(3), is(equalTo("GET /final Final")));
     }
 
-    private static RequestModel requestModel(String method, String url) {
+    private static RequestModel requestModel(RequestMethod method, String url) {
         RequestModel request = new RequestModel();
-        request.setMethod(RequestMethod.GET);
+        request.setMethod(method);
         request.setUrl(url);
         request.setHeaders(Collections.emptyList());
         request.setBody("");
```
If you really want to also test in the definitions it's better to create a specific test for that.

**Comment by naggingant** [comment]
Thanks, makes much sense. Indeed, that wasn't a unit test...
I would like to just apply your suggestion, as there was nothing i could think of to add.
(The only thing could be that the server is started on every case, but I suppose that is no concern here)

**Comment by thc202** [comment]
Yeah, thought on that too, it's still fast so not a big problem (IMO).

**Comment by thc202** [comment]
Needs a `spotlessApply` to fix the formatting.

**Comment by naggingant** [comment]
Applied, the check passed locally. Probably I shouldn't have force-pushed these changes but at least the history didn't become messy :sweat:

**Comment by thc202** [comment]
It's fine to force push :)

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Review by ricekot — APPROVED** [review]
Thanks!

**Pull request merged**
