### PR TITLE
Sequence - use new seq scan in desktop

### PR DESCRIPTION
**Pull request by psiinon**
## Overview
Switch to use the new seq ascan - it works better and is faster.
We should revisit the help at some point.

## Related Issues
https://github.com/zaproxy/zap-extensions/pull/5897 - mayneed to change to use this for the default policy

## Checklist
- [ ] Update help
- [ ] Update changelog
- [ ] Run `./gradlew spotlessApply` for code formatting
- [ ] Write tests
- [ ] Check code coverage
- [ ] Sign-off commits
- [ ] Squash commits
- [ ] Use a descriptive title

For more details, please refer to the [developer rules and guidelines](https://www.zaproxy.org/docs/developer/dev-rules-and-guidelines/).

### CODE REVIEW

**Review by kingthorin — COMMENTED** [review]
Update help and changelog?

**Comment by psiinon** [comment]
Have updated the changelog. We have another task for updating the help, that might take more effort :)

**Review by kingthorin — APPROVED** [review]
Haven't tested but seems reasonable

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
