### PR TITLE
graphql: use Spider add-on

### PR DESCRIPTION
**Pull request by thc202**
Add extension that depends on the spider add-on and adds a custom
spider parser.
Extract common spider parser code into helper class and update existing
parser accordingly.

Part of zaproxy/zaproxy#3113.

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]

**Review by psiinon — APPROVED** [review]

**Review by ricekot — APPROVED** [review]
Thank you!

**Comment by thc202** [comment]
From IRC talks, I missed migrating the spider filter and use of `ValueGenerator`, will do that shortly.

**Comment by kingthorin** [comment]
Oops, and we all missed it too.

**Comment by thc202** [comment]
Being done in #3955.

**Pull request merged**
