### PR TITLE
QuickStart - cope with LaF switching

### PR DESCRIPTION
**Pull request by psiinon**
This is not perfect - some of the text backgrounds turn grey, but its much better than the current code handles Look and Feel switching ;)
Havnt updated the ChangeLog as this is related to the dark mode handling..

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]
Haven't tested but looks good.

**Comment by psiinon** [comment]
Part of https://github.com/zaproxy/zaproxy/pull/6202

**Comment by thc202** [comment]
Changes look good but the commit message could be amended.

**Comment by psiinon** [comment]
Commit message tweaked as it now appears to be working well.

**Review by kingthorin — APPROVED** [review]
Thanks

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
