### PR TITLE
Auto: reset passive scan configs

### PR DESCRIPTION
**Pull request by psiinon**
Not sure if all jobs should do this, but I think this is the most important one to support this - quite a few people have been confused by this problem, including me 😛 

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Comment by psiinon** [comment]
tests fixed 😁

**Review by ricekot — APPROVED** [review]
Thanks!

**Review by kingthorin — COMMENTED** [review]
Thank you for tackling this!

**Pull request merged**
