### PR TITLE
replacer: update ZAP to 2.10.0

### PR DESCRIPTION
**Pull request by thc202**
Update ZAP to 2.10.0.
Use Log4j 2 APIs.

Part of zaproxy/zaproxy#6376.

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]
LGTM, Thanks!

**Review by psiinon — APPROVED** [review]

**Comment by thc202** [comment]
Add missed one in this PR too...

**Comment by thc202** [comment]
Rebased to include the changes done in #2797 and fixed the missed log statement.

**Review by kingthorin — APPROVED** [review]
TY!

**Pull request merged**
