### PR TITLE
Automation: Dont switch tabs

### PR DESCRIPTION
**Pull request by psiinon**
Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Review by ricekot — APPROVED** [review]
Thanks!

**Review by kingthorin — APPROVED** [review]
You fixed the item I was going to point out :grinning:, while I was reviewing things.

**Review by thc202 — APPROVED** [review]

**Comment by psiinon** [comment]
Reported by @thc202 and @ricekot in IRC :P

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
