### PR TITLE
fuzz: fix typo

### PR DESCRIPTION
**Pull request by njmulsqb**
Spelling mistake

### CODE REVIEW

**Comment by thc202** [comment]
Please, update the changelog.

**Comment by njmulsqb** [comment]
> Please, update the changelog.
> 
> Commit should be signed off.

Sorry, I dont know how is that done. Please explain

**Comment by thc202** [comment]
1. https://github.com/zaproxy/zap-extensions/blob/e01f51df9c6aa30754657d92bafdcff488f900f8/CONTRIBUTING.md#changelog https://github.com/zaproxy/zap-extensions/blob/e01f51df9c6aa30754657d92bafdcff488f900f8/addOns/fuzz/CHANGELOG.md
2. https://github.com/zaproxy/zap-extensions/pull/3127/checks?check_run_id=3521560183

**Comment by njmulsqb** [comment]
> Please, update the changelog.
> 
> Commit should be signed off.

All done

**Comment by njmulsqb** [comment]
Any update on this PR merger? @thc202

**Comment by thc202** [comment]
The typo is no longer being fixed, it also contains other commit.

**Comment by thc202** [comment]
Addressed.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Review by kingthorin — APPROVED** [review]

**Comment by kingthorin** [comment]
@njmulsqb how would you like to be listed in the credits? (Name, twitter/github link, etc) Have a look at how others are listed and let us know.

https://www.zaproxy.org/docs/desktop/credits/#zap-extended-team

**Comment by njmulsqb** [comment]
> @njmulsqb how would you like to be listed in the credits? (Name, twitter/github link, etc) Have a look at how others are listed and let us know.
> 
> https://www.zaproxy.org/docs/desktop/credits/#zap-extended-team
> 

Najam Ul Saqib (https://www.twitter.com/njmulsqb)

**Comment by kingthorin** [comment]
Alpha by last name.

**Pull request merged**
