### PR TITLE
fix: Eval Villain workflow follow redirects to save properly

### PR DESCRIPTION
**Pull request by kingthorin**
Related to: zaproxy/zaproxy#7008

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
I’ll fix the CHANGELOG in the PR when the job has run.

**Comment by thc202** [comment]
Sounds good.

**Review by thc202 — APPROVED** [review]

**Comment by psiinon** [comment]
Looks like its run now :)

**Review by psiinon — APPROVED** [review]

**Comment by psiinon** [comment]
Either way is fine by me ;)

**Comment by kingthorin** [comment]
I meant after I run this fixed workflow I'll tweak the PR it generates :wink:

**Pull request merged**
