### PR TITLE
Selenium: Support Firefox profiles

### PR DESCRIPTION
**Pull request by psiinon**
## Overview
Briefly describe the purpose, goals, and changes or improvements made in this pull request.

## Related Issues
Specify any related issues or pull requests by linking to them.

## Checklist
- [x] Update help
- [x] Update changelog
- [x] Run `./gradlew spotlessApply` for code formatting
- [x] Write tests
- [x] Check code coverage
- [x] Sign-off commits
- [x] Squash commits
- [x] Use a descriptive title

For more details, please refer to the [developer rules and guidelines](https://www.zaproxy.org/docs/developer/dev-rules-and-guidelines/).

### CODE REVIEW

**Comment by psiinon** [comment]
Plan to add help, but the code should be complete.

**Comment by psiinon** [comment]
Help added .. will also add some unit tests..

**Comment by psiinon** [comment]
Tests done, ready for review 😁

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Comment by psiinon** [comment]
@kingthorin look ok to you?

**Review by kingthorin — APPROVED** [review]

**Pull request merged**
