### PR TITLE
improve: various: SAST (sonar) replace type spec with diamond operator

### PR DESCRIPTION
**Pull request by kingthorin**
Address finding "Replace the type specification in this constructor call with the diamond operator ("<>")."

CHANGELOGS updated with change note where warranted.

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by thc202** [comment]
There are still places where the type argument can be removed.

**Comment by kingthorin** [comment]
There are a number of instances like: `new JComboBox<>(new SortedComboBoxModel<String>())` where I couldn't see how to address the inner one without separately instantiating another object. Is that the right move?

**Comment by thc202** [comment]
> Is that the right move?

I was not referring to those cases, those are fine. I was referring to e.g.: `CrossSiteScriptingScanRuleUnitTest`, `ILS`, `OpenApiUnitTest`, `SqlInjectionScanRule`, `UserControlledCookieScanRuleUnitTest`, `UserControlledOpenRedirectScanRuleUnitTest`, `UsernameEnumerationScanRule`.

**Comment by kingthorin** [comment]
Thanks, missed that comment somehow.

**Comment by kingthorin** [comment]
> > Is that the right move?
> 
> I was not referring to those cases, those are fine. I was referring to e.g.: `CrossSiteScriptingScanRuleUnitTest`, `ILS`, `OpenApiUnitTest`, `SqlInjectionScanRule`, `UserControlledCookieScanRuleUnitTest`, `UserControlledOpenRedirectScanRuleUnitTest`, `UsernameEnumerationScanRule`.

I was only able to find them and fix them in these classes:
```
modified:   addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRuleUnitTest.java
modified:   addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/v1/OpenApiUnitTest.java
modified:   addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/v2/OpenApiUnitTest.java
modified:   addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/v3/OpenApiUnitTest.java
modified:   addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/UserControlledCookieScanRuleUnitTest.java
modified:   addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/UserControlledOpenRedirectScanRuleUnitTest.java
```

And that was with regex searching not sonarlint :wink: (skipped ILS as discussed)

**Comment by thc202** [comment]
`SqlInjectionScanRule` lines 1205 and 1209.
`UsernameEnumerationScanRule` lines 644 and 647.

Note that the above comment was not an exhaustive list ;) I'll have to check again which ones are missing.

**Comment by kingthorin** [comment]
Thanks, got those two now as well.

**Comment by kingthorin** [comment]
Found some more with regex searches.

**Comment by thc202** [comment]
- `AjaxSpiderAPI` line 407 and 544
- `OpenApiPrimitivesInBody` line 73
- `ReplacerAPI` line 221
- `WappalyzerAPI` line 100
- `WappalyzerJsonParser` line 173
- `WappalyzerJsonParserUnitTest` line 35
- `WebSocketAPI` line 426

**Comment by kingthorin** [comment]
Thanks

**Comment by thc202** [comment]
No problem.

**Comment by kingthorin** [comment]
Hopefully that's all of them :wink:

**Comment by thc202** [comment]
Fine to fix up now for me (I didn't spot any).

**Comment by thc202** [comment]
This has conflicts now.

**Comment by kingthorin** [comment]
Sorted 👍

**Comment by thc202** [comment]
The change in `ZestPopupNodeCopyOrCut` was lost though.

**Comment by kingthorin** [comment]
Thanks/sorry.

Conflict resolution fail 😞

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
No worries and thank you!

**Review by psiinon — APPROVED** [review]

**Pull request merged**
