### PR TITLE
network: update dependencies

### PR DESCRIPTION
**Pull request by thc202**
Update the following dependencies:
 - Netty, 4.1.73.Final → 4.1.81.Final;
 - Bouncy Castle, 1.69 → 1.70.

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]

**Comment by kingthorin** [comment]
Add maintenance note to CHANGELOG?

**Comment by thc202** [comment]
I will have to update the changelog to mention all the features added since last release (e.g. connection options, new client implementation).

**Comment by kingthorin** [comment]
Another PR then?

**Comment by thc202** [comment]
Yes, I still want to do some more changes.

**Comment by kingthorin** [comment]
Great 👍

**Review by ricekot — APPROVED** [review]

**Pull request merged**
