### PR TITLE
Latest files from Crowdin

### PR DESCRIPTION
**Pull request by zapbot**
Autogenerated PR from zapbot

### CODE REVIEW

**Comment by kingthorin** [comment]
How do we get people to read the file for comments/context?

**Comment by thc202** [comment]
With these messages it might go easily unnoticed because of the length of the string...
We should probably not i18n these with resource messages, we shouldn't tie the locale of ZAP to the (possible) locale of the target server?

**Comment by kingthorin** [comment]
Ya, you're right. It just isn't a good fit for this content in this location.

**Comment by thc202** [comment]
OK. Closing, will revert the changes in Crowdin and take a look at extracting the messages into other place.

**Pull request closed without merging**
