### PR TITLE
Reports - modern template WIP

### PR DESCRIPTION
**Pull request by psiinon**
Based on the templates in #2876 but implemented as themes.
The plan is to replace the tradition-html-plus template with this one.

I havnt done all of the themes yet, and they arent yet _exactly_ the same as the originals.
The chart is also much bigger - not sure if thats better or worse though ;)

Feedback on the approach appreciated.

Screenshots of the initial sections.

## Console
Screenshot_2021-05-17 ZAP Scanning Report(3)

## Construction
Screenshot_2021-05-17 ZAP Scanning Report(4)

## Corporate
Screenshot_2021-05-17 ZAP Scanning Report(5)

## Ocean
Screenshot_2021-05-17 ZAP Scanning Report(6)

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Comment by psiinon** [comment]
Tweaked the charts to be 75% of the width - can easily change that via the custom or theme specifc css now...

**Comment by Scopestyle** [comment]
Hey @psiinon that's awesome! Do you have an elegant solution to adjust the font color for the chart as well? If that works I can use this example to finish the rest! 😃

**Comment by psiinon** [comment]
I have a solution, but I dont know if its "elegant" :P 
The css files include a new set of styles like:
```
.risk-3-chart {
        background-color: red;
}
.risk-2-chart {
        background-color: orange;
}
.risk-1-chart {
        background-color: yellow;
}
.risk-0-chart {
        background-color: blue;
}
```
These are then used in the report in hidden divs:
```
        			<!--  Hidden divs just to allow us to get hold of the right CSS colors -->
        			<div class="risk-3-chart" style="display: none;"></div>
        			<div class="risk-2-chart" style="display: none;"></div>
        			<div class="risk-1-chart" style="display: none;"></div>
        			<div class="risk-0-chart" style="display: none;"></div>
```
Those styles can then be used in the JS:
```
        const chartHigh = getComputedStyle(document.querySelector('.risk-3-chart')).backgroundColor;
        const chartMed = getComputedStyle(document.querySelector('.risk-2-chart')).backgroundColor;
        const chartLow = getComputedStyle(document.querySelector('.risk-1-chart')).backgroundColor;
        const chartInfo = getComputedStyle(document.querySelector('.risk-0-chart')).backgroundColor;
```
I did try to reuse the stles like `risk-3` but the values in construction.css broke that ;)

**Comment by thc202** [comment]
Can this be closed with #2961?

**Comment by psiinon** [comment]
Yes, this ones no longer needed.

**Pull request closed without merging**
