### PR TITLE
webuipoc: Site tree indentation

### PR DESCRIPTION
**Pull request by Moeez905**
WIP issue https://github.com/zaproxy/zaproxy/issues/8287

### CODE REVIEW

**Comment by thc202** [comment]
Looks better but now there are horizontal scrollbars in almost all rows, it would be better to have a single one for the whole tree.

**Comment by psiinon** [comment]
And not to include the whole URL in each node of course, that will significantly reduce the need for scrolling.

**Comment by thc202** [comment]
The scrollbar is still showing with #5624:
scroll

**Comment by Moeez905** [comment]
> The scrollbar is still showing with #5624: scroll

On it

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Review by psiinon — APPROVED** [review]

**Comment by psiinon** [comment]
This makes the Sites Tree so much more usable!

**Pull request merged**
