### PR TITLE
Reports - Template Help Pages

### PR DESCRIPTION
**Pull request by psiinon**
Add help pages for the templates.

Summary:
Screenshot 2022-02-04 at 13 56 35

Screenshots / samples:
Screenshot 2022-02-04 at 13 57 05

Screenshot 2022-02-04 at 13 57 21

Screenshot 2022-02-04 at 13 57 38

Still WIP as I need to add the other reports, but submitting for initial feedback.

Any suggestions for improvements?

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
Needs spotlessApply?

**Comment by psiinon** [comment]
Yeah, didnt bother with that as its WIP ;)

**Comment by psiinon** [comment]
No longer WIP but I have changed the look and feel - will upload some screenshots when I get a chance but prob wont be this week :/

**Comment by psiinon** [comment]
Dont think the unit test failure is related to these changes ... rerunning the jobs...

**Comment by psiinon** [comment]
Tests passed :D
Ready to review - new screenshots: 

Screenshot 2022-02-07 at 09 54 49

Screenshot 2022-02-07 at 09 55 11

Screenshot 2022-02-07 at 09 55 31

Screenshot 2022-02-07 at 09 55 46

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Review by kingthorin — APPROVED** [review]

**Pull request merged**
