### PR TITLE
Generate and save CodeDx report with ReportLastScan.generate

### PR DESCRIPTION
**Pull request by RyanMcC**
Files.write in generateReportFile appears to sometimes cause exceptions from encoding conflicts. This uses the ReportLastScan.generate method that saves to a file internally instead. It also now parses the report file with an XMLEventReader to check if it's empty.

### CODE REVIEW

**Comment by thc202** [comment]
Could you update the [changelog](https://github.com/zaproxy/zap-extensions/blob/master/addOns/codedx/CHANGELOG.md) mentioning the change/fix?

**Comment by baffles** [comment]
@thc202 - should be updated now!

**Comment by thc202** [comment]
Thanks!

**Comment by thc202** [comment]
@baffles do you have any other changes planned or good to release?

**Comment by baffles** [comment]
Nope that's all for now!

**Comment by thc202** [comment]
The new version is now available in the marketplace.

**Pull request merged**
