### PR TITLE
ZAP Report Competition Themes

### PR DESCRIPTION
**Pull request by Scopestyle**
Hey guys, 

I created a few themes for the ZAP Report Competition. 

Kind regards, 

Erik

### CODE REVIEW

**Comment by kingthorin** [comment]
To address the DCO requirement you'll need to sign-off the commit(s):

- https://github.com/zaproxy/zaproxy/blob/develop/CONTRIBUTING.md#developer-certificate-of-origin
- https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff

**Comment by Scopestyle** [comment]
DCO is now fixed.

**Comment by psiinon** [comment]
Thanks for submitting these!
They definitely look better than our current reports, so I'm all for including _some_ of them.
However it does look like they are mostly (all?) just different colours / css?
I dont have a problem with this but we were really hoping to get a set of reports that looked significantly different from each other rather than with different colours.
The way we have structured the templates also makes this difficult to manage going forwards as there is a lot of repetition.

So one option would be for us to enhance templates so that the theme (?) is a property of the template. The user would be able to select this new template (zap-modern??) and then have a pull down of all of the themes you have provided.
We would need to discuss what this would mean in terms of the competition - I dont think it should count as 10 templates but I'm also happy for it to count as more than 1.

thoughts from anyone else?

**Comment by Scopestyle** [comment]
Hey @psiinon, thank you for your feedback. 

I really spent a lot of time to give each template its own identity. I only changed what I felt was important to keep the html clean, and customizable. (In my interpretation that means, if you would change the fonts and colors of the template, they would still be unique templates from one another). You also noticed with how I added the themes that I had some concerns on how to organize these myself 😅

You make a fair point to differentiate themes from templates, I'm not a ZAP end user, or security specialist, I don't really know what other data to present other than what's offered in the default template. But it's open source so in the end any template that makes the cut can easily grow with the project.

**Comment by psiinon** [comment]
FYI I'm now adding theme support to the reporting add-on ;)

**Comment by psiinon** [comment]
Theme support added via #2882

**Comment by psiinon** [comment]
@Scopestyle we've had a chat in the ZAP core team.
We really like your templates and would like to use them :)

Would you be ok reworking them to be just one template but with multiple themes (after #2882 has been merged)?
Would you be ok with a reward of $200 for the PR?

As mentioned before we would really like a set of very different styles of reports. We only have ~ 1k to spend on this and dont want to spend all of that on one format with multiple themes. However we do like what you've done and appreciate the amount of work you have put into it.
If you don't think thats fair then we can talk about it some more. You can of course withdraw your PR or remove some of the themes, we don't want to take advantage of your work based on any misunderstandings.

**Comment by psiinon** [comment]
FYI #2882 has been merged. Let me know if you need any advice / guidance / help converting your PR to use themes.

**Comment by Scopestyle** [comment]
Hi @psiinon I'm just looking forward to having the means to replace my broken desk chair 😅 and if the full budget comes from OWASP I get it. So no issues from my end. Could you give me some insight as to what I have to do to make the themes compatible?

**Comment by psiinon** [comment]
Great!

So what you need is just one directory under [reports](https://github.com/zaproxy/zap-extensions/tree/master/addOns/reports/src/main/zapHomeFiles/reports)

The template.yaml file should have a new 'themes' section with a list of theme 'keys', as per https://github.com/zaproxy/zap-extensions/blob/master/addOns/reports/src/main/zapHomeFiles/reports/traditional-html-plus/template.yaml

Each theme key should have a display string in the Message.properties file, as per https://github.com/zaproxy/zap-extensions/blob/master/addOns/reports/src/main/zapHomeFiles/reports/traditional-html-plus/Messages.properties#L14-L15

Extract any common CSS into a common file which should live in the resources directory, then add one specific css file per theme.
The 2 include statements in the html can look like: https://github.com/zaproxy/zap-extensions/blob/master/addOns/reports/src/main/zapHomeFiles/reports/traditional-html-plus/report.html#L6-L9

The `reportData.theme` value will be the theme key (not dispay name) and will be set by the UI.

Example common and theme specific css files are:
* https://github.com/zaproxy/zap-extensions/blob/master/addOns/reports/src/main/zapHomeFiles/reports/traditional-html-plus/resources/common.css
* https://github.com/zaproxy/zap-extensions/blob/master/addOns/reports/src/main/zapHomeFiles/reports/traditional-html-plus/resources/dark.css
* https://github.com/zaproxy/zap-extensions/blob/master/addOns/reports/src/main/zapHomeFiles/reports/traditional-html-plus/resources/light.css

Does that all make sense?

FYI you should run the `:addOns:reports:clean` gradle task before updating the PR - this will format the HTML, otherwise the build will fail.

Any more questions then just ask here :)

**Comment by Scopestyle** [comment]
Hey @psiinon  could you elaborate on the `:addOns:reports:clean` gradle task? I have no idea what that means.

**Comment by kingthorin** [comment]
Are you using an IDE for development?

**Comment by Scopestyle** [comment]
@kingthorin No, just Notepad++ to edit the theme files. I also think I need some further guidance on how to actually test the new theme functionality in ZAP. I need to edit a lot and I have no idea if any of it comes out right.

**Comment by kingthorin** [comment]
There are developer docs here: https://www.zaproxy.org/docs/developer/

I'd suggest going with Eclipse as that's what the core team use and are familiar with, but there are also some IntelliJ details there as well.

**Comment by psiinon** [comment]
You dont need an IDE or even a ZAP development environment to test the new report templates :)
Open the report dialog and select the "Options" tab.
The "Template Directory" specifies where ZAP is picking the templates up from. You can either copy your template(s) into this directory and restart ZAP, or you can change that field to point to the directory you are using, the one which contains all of the template sub directories. That should take effect immediatelly and you updated templates should be usable.
ZAP always reads the templates from disk so you dont need to restart ZAP if you have just changed the contents of the templates or the files they are using.
To get some data into ZAP then you can run an automated scan against a suitable site, eg http://www.webscantest.com/ or an other site on https://owasp.org/www-project-vulnerable-web-applications-directory/
You can stop the scan at any time rather than waiting for it to complete, you just need some example alerts.

Re the "clean" task, just runn the following command in the top level "zap-extensions" folder:
`./gradlew :addOns:reports:clean` - thats it :)

**Comment by Scopestyle** [comment]
Hi @psiinon I get how I to test the standard templates, that's exactly how I build the original ones. But I would like to test the new themes segment you built. Any chance you could assist me with getting that to show up like in your screenshot? I'm on the #zaproxy IRC channel if you could spare a moment.

**Comment by psiinon** [comment]
@Scopestyle sorry I'd finished work by then :/ I'm usually on irc UK work hours.
I can also update and test your PR if you like - that shouldnt take me very long ;)
But also v happy to walk you through the process ...

**Comment by psiinon** [comment]
@Scopestyle would you like some help on this? I'm happy to update it - we're looking for good templates not git skills :)

**Comment by Scopestyle** [comment]
Hey @psiinon sorry I've had no time at all past week. Truth be told I have limited knowledge on GIT, or IDEs at all. I would love some help to get an updated ZAP .exe version where I can just test the templates. Is that something you could help me with?

**Comment by psiinon** [comment]
@Scopestyle you dont actually need any knowledge of GIT or IDEs .. well, just a little maybe.

1. Download ZAP from https://www.zaproxy.org/download/
2. Install the `Report Generation` add-on
3. Run ZAP and open the 'Generate Report' dialog
4. Switch to the 'Options' tab and change the 'Template Directory' to point to the zap-extensions directory where you are making your changes

ZAP will now reload the templates in that directory. It will pick up any changes you make apart from changes to the 'template.yaml' file - you'll have to restart ZAP to get those.

You will need to run ZAP against a test site in order to get some reports though...

**Comment by psiinon** [comment]
FYI I'm working on a new PR to add these themes...

**Comment by psiinon** [comment]
@Scopestyle and anyone else interested in this PR - my initial attempt is https://github.com/zaproxy/zap-extensions/pull/2933

Feedback and improvements appreciated :)

**Comment by thc202** [comment]
Follow up on #2961.

**Pull request closed without merging**
