### PR TITLE
Move `ValueGenerator` from core and rename it

### PR DESCRIPTION
**Pull request by thc202**
Move the `ValueGenerator` interface to the `commonlib` add-on and rename it to `ValueProvider` to avoid duplicated names. Add the default implementation as well.
Change all other add-ons to use the interface/implementation from the `commonlib` add-on.
Change the `formhandler` add-on to depend on `commonlib` and set the implementation that provides the custom values.

Part of zaproxy/zaproxy#8016.

### CODE REVIEW

**Comment by kingthorin** [comment]
Nothing needed for the Ajax Spider?

**Comment by thc202** [comment]
It does not use it.

**Review by kingthorin — APPROVED** [review]

**Comment by kingthorin** [comment]
Should we unify for handler and this at some point? Is there value or benefit in keeping them separate?

**Comment by thc202** [comment]
What's "this"?

**Review by psiinon — APPROVED** [review]

**Pull request merged**
