### PR TITLE
amf: retire add-on

### PR DESCRIPTION
**Pull request by thc202**
Remove all files of the add-on, the dependencies are no longer always available and the add-on is less important with Flash no longer being supported.

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]
It's not included in weeklies right?

**Comment by thc202** [comment]
Right.

**Comment by kingthorin** [comment]
Drop the help content after this one is done? https://www.zaproxy.org/docs/desktop/addons/amf-support/

**Comment by thc202** [comment]
That's the plan.

**Review by ricekot — APPROVED** [review]
Thanks!

**Pull request merged**
