### PR TITLE
Active Scanning addition: SSTI

### PR DESCRIPTION
**Pull request by dvas0004**
Initial commit to add Active Scanning for Server Side Template Injection (https://www.we45.com/blog/server-side-template-injection-a-crash-course-)

### CODE REVIEW

**Comment by dvas0004** [comment]
Some screenshots to show operation:

image

image

image

**Comment by thc202** [comment]
This is already being worked on (per zaproxy/zaproxy#2332), scanner in https://github.com/DiogoMRSilva/zap-extensions/tree/pullRequestMaster/src/org/zaproxy/zap/extension/sstiscanner

More details on what the scanner catches: https://github.com/DiogoMRSilva/websitesVulnerableToSSTI

**Comment by dvas0004** [comment]
Ah missed it!

Fair enough thanks a lot!! :)

**Comment by thc202** [comment]
Closing, per previous comments.

**Pull request closed without merging**
