### PR TITLE
Updated to pre 2.6.0 jar plus associated changes

### PR DESCRIPTION
**Pull request by psiinon**

### CODE REVIEW

**Comment by psiinon** [comment]
OK, this should be ready for review now

**Comment by psiinon** [comment]
@kingthorin this look ok? There are some more pnh changes I'll need to make, but will have to do those later

**Comment by kingthorin** [comment]
Do the associated ZapAddOn.xml need `not-before-version` updates?

**Comment by thc202** [comment]
Yes, some of them (PnH, WebSockets and Quick Start?) need that updated (I remembered checking the version of the add-ons but not that :/ ).

**Comment by psiinon** [comment]
All the add-ons released to date have been built with the 2.5.0 jar. From now on we cant really release any more add-ons until 2.6.0 is out, and those ones should have the not-before-version updated.

**Comment by thc202** [comment]
Cool.

**Comment by kingthorin** [comment]
Ok

**Pull request merged**
