### PR TITLE
zaproxy/zaproxy issue #1986 Move Integer Overflow from Alpha to Beta

### PR DESCRIPTION
**Pull request by msrader**
I want to get this moved to the next level.

### CODE REVIEW

**Comment by thc202** [comment]
Changes look good, though the pull request should be merged only after the release of the active scanner add-ons (done during release of ZAP 2.4.3).

In the meantime could you open a pull request to change the alpha version of the scanner, to add the technology check?

**Comment by msrader** [comment]
If you look the alpha version (which the changes have already been pulled) has the technology check in it.

**Comment by thc202** [comment]
The latest version of the Integer Overflow scanner in alpha does not yet have the tech check:
https://github.com/zaproxy/zap-extensions/blob/02201e7106965d710f2bb1badb265909ca39e1ef/src/org/zaproxy/zap/extension/ascanrulesAlpha/IntegerOverflow.java

The last commit just added the check of the status code.

**Comment by msrader** [comment]
Humm, that's strange, because its in the beta.  Ok, I'll add it tonight.

**Comment by msrader** [comment]
Added the code.

**Comment by thc202** [comment]
Change merged.

**Comment by thc202** [comment]
Thank you.

**Pull request merged**
