### PR TITLE
chore: httpsinfo & tlsdebug: Remove add-ons being retired

### PR DESCRIPTION
**Pull request by kingthorin**
Per: https://github.com/zaproxy/zaproxy/issues/6918

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
Should I also open a zap-admin PR removing them from the 2.11 XML?

**Comment by thc202** [comment]
Yes, please, they will also be removed from the website. We also need to remove them from Crowdin.

**Comment by kingthorin** [comment]
I found the functionality in Crowdin, shall I go ahead or wait until the PRs are merged?

**Comment by thc202** [comment]
Might be better to wait, just in case.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

Once this is merged we can remove from Crowdin.

**Comment by kingthorin** [comment]
@psiinon can we merge this one? If someone decides to pick one or both of them up they'll still exist in the repo history.

**Review by psiinon — APPROVED** [review]

**Comment by kingthorin** [comment]
They've been removed from Crowdin.

**Comment by thc202** [comment]
The help files are still there though.

**Comment by kingthorin** [comment]
Oops got those now too.

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
