### PR TITLE
Added unit test for CharsetMismatchScanner class

### PR DESCRIPTION
**Pull request by rscipien**
Test for issue [2799](https://github.com/zaproxy/zaproxy/issues/2799)
There is probably one bug, unit test implemented for this bug in method differentMetaAndHeaderPlusAdditionalMetaParametersHtml.

### CODE REVIEW

**Comment by kingthorin** [comment]
Tests failing

**Comment by thc202** [comment]
The failing test should be ignored (with the annotation) or fixed, latter is the ideal.

**Comment by thc202** [comment]
Some of the comments are being added to the commit instead of the pull request, though they are reflected here there's no (email) notification for those.

**Comment by rscipien** [comment]
Count of alert is sufficient for testing ? Maybe we should check for type of error ? But it probably required some changes in CharsetMismatchScanner

**Comment by thc202** [comment]
For scanners that raise multiple alerts we should check that it's being raised the correct alert, changes done in #550 should allow to do that (see #546 for example usage, although for this scanner it might need some changes, use a matcher that checks if it contains the name).
We should also check other properties of the alert (scanner ID, CWE/WASC ID, HTTP message, risk, confidence...).

**Comment by thc202** [comment]
#550 now has a "contains matcher" for the name (`containsNameLoadedWithKey`).

**Comment by rscipien** [comment]
Add containsOtherInfoLoadedWithKey to ScannerTestUtils. For xml test you can't check alert by name

**Comment by psiinon** [comment]
Sorry for the delays in reviewing this.
It looks good except that it doesnt seem to test the METACONTENTTYPE_METACHARSET_MISMATCH case.
Might also be nice to have a test for no content type?

**Comment by rscipien** [comment]
Added test:
shouldRaiseAlertWhenDifferentMetaCharsetAndContentType
shouldPassWhenNoContentType

**Comment by kingthorin** [comment]
Looks good to me

**Pull request merged**
