### PR TITLE
fuzz: allow circular redirects always

### PR DESCRIPTION
**Pull request by thc202**
Remove the call that was disabling circular redirects always, also,
remove code that's no longer used/needed.

Related to zaproxy/zaproxy#7256.

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]
Is there anything in the help that needs to be updated?

**Comment by thc202** [comment]
No, the option was not exposed to the user (and was not documented).

**Comment by kingthorin** [comment]
DOH, needs a spotlessApply.

**Comment by thc202** [comment]
Done.

**Review by psiinon — APPROVED** [review]

**Pull request merged**
