### PR TITLE
network: add base server

### PR DESCRIPTION
**Pull request by thc202**
Add server which provides the basic functionality.

### CODE REVIEW

**Review by psiinon — APPROVED** [review]

**Review by kingthorin — APPROVED** [review]

**Comment by kingthorin** [comment]
Re-running all checks, this shouldn't take 5 hours.

**Comment by kingthorin** [comment]
Finally finished, merged.

**Comment by kingthorin** [comment]
FYI, don’t get side tracked on this but I wanted to make you aware of it so it can be investigated later: https://github.com/zaproxy/zap-extensions/runs/4946556739?check_suite_focus=true

```bash
> Task :addOns:network:test
1232

1233
BaseServerUnitTest > shouldStopServerAndActiveConnections() FAILED
1234
    java.lang.AssertionError: 
1235
    Expected: is <0>
1236
         but: was <1>
1237
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
1238
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
1239
        at org.zaproxy.addon.network.internal.server.BaseServerUnitTest.shouldStopServerAndActiveConnections(BaseServerUnitTest.java:324)
1240

1241
330 tests completed, 1 failed
1242

1243
> Task :addOns:network:test FAILED
1244

1245
FAILURE: Build failed with an exception.
1246
657 actionable tasks: 22 executed, 251 from cache, 384 up-to-date
1247

1248
* What went wrong:
1249
Execution failed for task ':addOns:network:test'.
1250
> There were failing tests. See the report at: file:///home/runner/work/zap-extensions/zap-extensions/addOns/network/build/reports/tests/test/index.html
1251

1252
* Try:
1253
> Run with --stacktrace option to get the stack trace.
1254
> Run with --info or --debug option to get more log output.
1255
> Run with --scan to get full insights.
1256

1257
* Get more help at https://help.gradle.org
1258

1259
BUILD FAILED in 51s
1260
Error: Process completed with exit code 1.
```

**Comment by thc202** [comment]
I saw this one locally too and thought it was fixed in the latest changes, it's a racing condition in the test, not all client side connections might have been closed just yet when that's checked… I could change to actively wait in the test client instead.

**Comment by thc202** [comment]
The change in #3499 should address the test failures.

**Pull request merged**
