### PR TITLE
exim: Fix duplicate "Save URLs..." options

### PR DESCRIPTION
**Pull request by ricekot**
## Overview
- Duplicate or missing "Save URLs..." entries in the Export menu.
- The "Save All URLs..." export option was saving only the selected URLs.

## Checklist
- [x] Update help
- [x] Update changelog
- [x] Run `./gradlew spotlessApply` for code formatting
- [ ] Write tests
- [ ] Check code coverage
- [x] Sign-off commits
- [x] Squash commits
- [x] Use a descriptive title

### CODE REVIEW

**Comment by psiinon** [comment]
I think we should discuss these changes first 😁

**Comment by ricekot** [comment]
https://github.com/zaproxy/zap-extensions/pull/6012#issuecomment-2545247710

Sure, but in any case we should fix the duplicate items in the Export menu
image

**Comment by psiinon** [comment]
Logo
**Checkmarx One – Scan Summary & Details** – [49938798\-4409\-411a\-8d67\-cc9d556c1d5e](https://eu.ast.checkmarx.net/projects/0da811fa-6373-42b1-bbb6-d0026285b136/scans?id=49938798-4409-411a-8d67-cc9d556c1d5e&branch=ricekot%2Fexim%2Fremove-export-urls)
### No New Or Fixed Issues Found

**Comment by ricekot** [comment]
Updated with the approach we discussed offline.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Review by kingthorin — APPROVED** [review]
Thanks

**Pull request merged**
