### PR TITLE
Fixes #4961 by adding appropriate accept headers.

### PR DESCRIPTION
**Pull request by tushar-97**
Fix zaproxy/zaproxy#4961

### CODE REVIEW

**Comment by tushar-97** [comment]
Fixes issue#4961

**Comment by thc202** [comment]
Thanks!

**Comment by thc202** [comment]
@tushar-97 how would you like to be credited?
https://github.com/zaproxy/zap-core-help/wiki/HelpCredits

**Comment by tushar-97** [comment]
Umm, My full name is Tushar Aggarwal. Is that the info your require? @thc202

**Comment by thc202** [comment]
Yes, that's good, a name/handle will do.

**Pull request merged**
