### PR TITLE
commonlib: add solution for HTTP response smuggling

### PR DESCRIPTION
**Pull request by jackdvd**
## Overview
Adds the solution section to the alert "HTTP Response Smuggling".

### CODE REVIEW

**Comment by jackdvd** [comment]
recheck

**Comment by jackdvd** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by thc202** [comment]
You need to configure your GitHub account to have the same email as the commits.

**Comment by thc202** [comment]
Better just push the new commits (though given the usage of the default branch that might as well end up closing the PR anyway).

**Pull request closed without merging**
