### PR TITLE
gettingStarted: update for 2.12

### PR DESCRIPTION
**Pull request by psiinon**
Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Comment by psiinon** [comment]
Have updated locally but am having problems pushing the changes ☹️

**Comment by psiinon** [comment]
OK, I may have to split this into multiple commits to see if they upload any better 😦

**Comment by psiinon** [comment]
And that worked 😛 
Ready for review again...

**Comment by thc202** [comment]
Thank you!

**Review by kingthorin — APPROVED** [review]

**Pull request merged**
