### PR TITLE
Combined all theme files in a single template.

### PR DESCRIPTION
**Pull request by Scopestyle**
I finally got around to combining all themes in a single template! Feedback welcome. 
Because this combines **all** previous themes feel free to close https://github.com/zaproxy/zap-extensions/pull/2876 

Kind regards,

Erik

### CODE REVIEW

**Comment by kingthorin** [comment]
Could you rebase your remove the unrelated commits?

**Comment by Scopestyle** [comment]
What does Rebate mean? I honestly have no idea what happend or what I could have done differently. I forked a clean repo, added my files and committed those. My CMD showed 19 files changed, but GitHub somehow changed 29. 
E2gD3v_XwAgmTjo

**Comment by kingthorin** [comment]
Cool so now that you’ve rebased your a `git push --force`

**Comment by thc202** [comment]
Follow up on #2961.

**Pull request closed without merging**
