### PR TITLE
Reports: add site parameter data

### PR DESCRIPTION
**Pull request by psiinon**
Added new sections to the trad-plus report and the modern one :)
Screenshot 2021-06-18 at 13-13-49 ZAP Scanning Report

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Comment by psiinon** [comment]
Ugh, will check the tests...

**Review by kingthorin — APPROVED** [review]
LGTM

**Comment by psiinon** [comment]
Added changelogs (inc missing comment for the modern template) - still need to add some help I think...

**Comment by psiinon** [comment]
Help added - suggestions for improving it gratefully received ;)

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Looks good to me. Thank you!

**Comment by odhiamboobuya** [comment]
error_page

Anything I may be missing? just pulled the code and built the addon

**Comment by odhiamboobuya** [comment]
> error_page
> 
> Anything I may be missing? just pulled the code and built the addon

Sorry, something with the Passing rules. Unchecking `Passing Rules` under `Sections` fixed it

**Comment by odhiamboobuya** [comment]
Still can't see the parameter data in the reports generated; tried all the available sample templates

**Comment by psiinon** [comment]
@odhiamboobuya did you build the add-on yourslef or use the latest weekly? If not then it wont have worked as that feature had not been released.
But it has been released now so update all of the add-ons and try again...

**Comment by odhiamboobuya** [comment]
> @odhiamboobuya did you build the add-on yourslef or use the latest weekly? If not then it wont have worked as that feature had not been released.
> But it has been released now so update all of the add-ons and try again...

Hello, had built the addon myself. Will try again as advised

**Pull request merged**
