### PR TITLE
Add Gradle Task to Check Dependency Updates

### PR DESCRIPTION
**Pull request by kingthorin**
Can be run as:
- `./gradlew addOns:ascanrules:dependencyUpdates`
- `./gradlew dependencyUpdates`

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
One minor detail: The task doesn't seem to appear in Eclipse's "Gradle Tasks" tab, so has to be used from the CLI.
(I think the convenience of having an option to check dependencies outweighs this minor detail.)

**Comment by psiinon** [comment]
Nice :)
Would it be possible to add a task to update the dependencies as well?

**Comment by kingthorin** [comment]
Not that I’ve found, I’m not sure how breaking changes would be handled. Will try to do some reading but I think this is the move for now 🤷‍♂️

**Comment by kingthorin** [comment]
After discussing with @thc202 a bit via IRC switched to a different plugin with greater contributor base and slightly different output:

<details>
<summary>Individual Add-on Example (click the triangle/control to the left to expand):</summary>

```bash
$ ./gradlew addOns:ascanrules:dependencyUpdates

> Task :addOns:ascanrules:dependencyUpdates

------------------------------------------------------------
:addOns:ascanrules Project Dependency Updates (report to plain text file)
------------------------------------------------------------

The following dependencies are using the latest milestone version:
 - org.apache.commons:commons-lang3:3.9

The following dependencies have later milestone versions:
 - com.googlecode.java-diff-utils:diffutils [1.2.1 -> 1.3.0]
     http://code.google.com/p/java-diff-utils/
 - org.bitbucket.mstrobel:procyon-compilertools [0.5.25 -> 0.5.36]
     https://bitbucket.org/mstrobel/procyon

Gradle release-candidate updates:
 - Gradle: [5.4.1 -> 6.2]

Generated report file C:\redacted\git\zap-extensions\addOns\ascanrules\build\dependencyUpdates\report.txt
```

</details>

**Comment by thc202** [comment]
Thanks!

**Comment by kingthorin** [comment]
FYI I did get this showing in Eclipse today using the Refresh button in the Gradle Tasks tab. (I'm not sure what that does that the "Gradle Refresh" package explorer context menu doesn't.)

**Pull request merged**
