### PR TITLE
a & p scanrulesAlpha: Prepare releases

### PR DESCRIPTION
**Pull request by kingthorin**
Update changelog with release date and link to tag

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by thc202** [comment]
There's a typo in `pscanrulesAlpha`. Was this meant for `ascanrulesAlpha`? (Not that does not worth releasing pscan.)

**Comment by kingthorin** [comment]
Yes yer right, let me tweak it.

**Comment by kingthorin** [comment]
Fixed. Yes I agree we may as well do pscanalpha for the SRI fix.

**Comment by thc202** [comment]
The typo was not fixed.

**Comment by kingthorin** [comment]
Ugh, okay I think it's finally sorted 🤦

**Comment by thc202** [comment]
Commit message still has it.

**Comment by kingthorin** [comment]
Oh my gosh, not my day. I'd committed it but not pushed it 🤦

**Comment by thc202** [comment]
Thanks!

**Pull request merged**
