### PR TITLE
Implemented new Extension Advanced Encoder Decoder

### PR DESCRIPTION
**Pull request by denniskniep**
Work in Progress...

ToDo:
- [x] Add Scripts for all functions that are currently in the "Encode/Decode/Hash" Dialog 
- [x] Provide the Layout of the "Encode/Decode/Hash" Dialog as Default Layout
- [x] Ability to return Errors from the script

### CODE REVIEW

**Comment by psiinon** [comment]
This pull request **introduces 1 alert** when merging 3329497576ed4a36d465522957c1bd86bf531831 into c000c38d87c4ef5f17b48d7583fea41c2a1d7a42 - [view on LGTM.com](https://lgtm.com/projects/g/zaproxy/zap-extensions/rev/pr-95888da67ccf8f7220c89d07e5acfe7bf5dee233)

**new alerts:**

* 1 for Useless null check

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by denniskniep** [comment]
The initial configuration is now like the existing "Encode/Decode/Hash..." Dialog

image

**Comment by denniskniep** [comment]
Not longer WIP. It is ready for review.

**Comment by thc202** [comment]
The pull request is now updated (after build changes, zaproxy/zaproxy#5302).

**Comment by kingthorin** [comment]
Grabbed this today to test it out. Had problems with the import and spotless, so I've rebased it.

**Comment by kingthorin** [comment]
Two quick things:

First:
You can remove all tabs and there's no way to restore the default set.

Second:
I un-installed and re-installed hoping to regain the default set of tabs:
```log
Uninstalled add-on Advanced Encoder version 1.0.0
Installing new add-on Advanced Encoder version 1.0.0
Failed to initialise extension org.zaproxy.zap.extension.advancedencoder.ExtensionAdvancedEncoder (from add-on [id=advancedencoder, version=1.0.0]), cause: InvalidParameterException: ScriptType already registered: encode-decode
java.security.InvalidParameterException: ScriptType already registered: encode-decode
	at org.zaproxy.zap.extension.script.ExtensionScript.registerScriptType(ExtensionScript.java:533)
	at org.zaproxy.zap.extension.advancedencoder.ExtensionAdvancedEncoder.hook(ExtensionAdvancedEncoder.java:105)
	at org.parosproxy.paros.extension.ExtensionLoader.startLifeCycle(ExtensionLoader.java:805)
	at org.zaproxy.zap.control.AddOnInstaller.installAddOnExtensionImpl(AddOnInstaller.java:291)
	at org.zaproxy.zap.control.AddOnInstaller.installAddOnExtensions(AddOnInstaller.java:272)
	at org.zaproxy.zap.control.AddOnInstaller.install(AddOnInstaller.java:92)
	at org.zaproxy.zap.control.AddOnLoader.addAddOnImpl(AddOnLoader.java:455)
	at org.zaproxy.zap.control.AddOnLoader.addAddon(AddOnLoader.java:428)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.install(ExtensionAutoUpdate.java:1322)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.installLocalAddOn(ExtensionAutoUpdate.java:481)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.installLocalAddOn(ExtensionAutoUpdate.java:438)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.access$2(ExtensionAutoUpdate.java:321)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate$2.actionPerformed(ExtensionAutoUpdate.java:261)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:356)
	at javax.swing.plaf.basic.BasicMenuItemUI$Actions.actionPerformed(BasicMenuItemUI.java:811)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1668)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:699)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706)
	at javax.swing.JMenuBar.processKeyBinding(JMenuBar.java:677)
	at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:307)
	at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:293)
	at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2974)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2966)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at java.awt.Component.processEvent(Component.java:6316)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:835)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1103)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:974)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:800)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Finished installing new add-on Advanced Encoder version 1.0.0
```

Now there's no longer a menu item under "Tools". (After a ZAP restart both the tabs and the menu item are back.)

**Comment by kingthorin** [comment]
Rebased current and fixed one previously noted issue.

**Comment by thc202** [comment]
Ref zaproxy/zaproxy#5656.

**Comment by kingthorin** [comment]
Rebased current. I'm looking at a reset button once again.

**Comment by kingthorin** [comment]
Added a reset button. It isn't perfect but it's a step forward. If your within session then it works fine, however if you close ZAP with some tabs removed then you can't reset afterward.

I need advice on setting/maintaining the default tab/outputpanel set from install time for later restoration.

**Comment by kingthorin** [comment]
@thc202 @psiinon I think this is ready for review now.

**Comment by denniskniep** [comment]
@kingthorin, @thc202  Many thanks for finalizing it :)

**Comment by kingthorin** [comment]
Np, thanks for putting it together

**Pull request merged**
