### PR TITLE
Extensions Leverage WritableFileChooser

### PR DESCRIPTION
**Pull request by kingthorin**
Update various extensions to leverage WritableFileChooser for saving and exporting.

Related to: zaproxy/zaproxy#5667 and zaproxy/zaproxy#5516

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
I ignored some of the reporting extensions based on previous discussions of them being unified/deprecated in favor of the Export Report addon.

**Comment by thc202** [comment]
https://github.com/zaproxy/zap-extensions/pull/2209/files#diff-08ff82ab75eb7b8114bd5f2a6e13cf35R234 could be removed (that's also in `TokenPanel`).

**Comment by kingthorin** [comment]
Fixed

**Comment by thc202** [comment]
In `TokenPanel` it was removed the one from load instead of save.

**Comment by kingthorin** [comment]
Oops, will tweak in about an hour. Thanks for catching that!

**Comment by kingthorin** [comment]
Fixed, sorry about that.

**Comment by thc202** [comment]
No problem. Thanks!

**Pull request merged**
