### PR TITLE
ascanrules: uncomment payloads for LFI tests

### PR DESCRIPTION
**Pull request by disenchant**
uncomment LFI strings that work for old PHP applications

### CODE REVIEW

**Comment by thc202** [comment]
The tests are failing, number of requests is greater now.
The changelog should be updated.
Commits need to be signed off.

**Comment by kingthorin** [comment]
These were purposefully commented out to address scan times, though I suppose they could be enabled but only used at INSANE strength.

**Comment by kingthorin** [comment]
@disenchant Do you plan to finish this?

**Comment by kingthorin** [comment]
@disenchant Do you plan to finish this?

Do you agree with https://developercertificate.org/ ?

**Comment by kingthorin** [comment]
I guess this can be closed?

**Comment by kingthorin** [comment]
Nothing further in over a month. Please re-open if you intend to finish it.

**Pull request closed without merging**
