### PR TITLE
Bugfix for groovy.lang.MissingMethodException

### PR DESCRIPTION
**Pull request by t4skforce**
Bugfix for Template raising Exception
```
ERROR org.zaproxy.zap.extension.scripts.OutputPanel  - groovy.lang.MissingMethodException: No signature of method: org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.getRequiredParamsNames() is applicable for argument types: () values: []
java.lang.RuntimeException: groovy.lang.MissingMethodException: No signature of method: org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.getRequiredParamsNames() is applicable for argument types: () values: []
```

### CODE REVIEW

**Comment by psiinon** [comment]
Thanks for this!
Could you add a line to the changelog? https://github.com/zaproxy/zap-extensions/blob/master/addOns/groovy/CHANGELOG.md

**Comment by thc202** [comment]
Those methods should be optional, could you provide the whole stacktrace? And version of Fuzzer and Groovy add-ons.

**Comment by t4skforce** [comment]
@thc202 sure

```
OWASP ZAP
Version: 2.9.0
---
Installed Add-ons: [..., [id=fuzz, version=12.0.0],..., [id=groovy,
version=2.0.0],...]
---
Operating System: Linux
Java Version: Debian 11.0.7-ea
...
```
Exception tested in this version (current Kali Linux). Full stacktrace is from a local DevBuild of zap but but same addons installed.

```
339906 [ZAP-FuzzerThreadPool-0-thread-1] ERROR org.zaproxy.zap.extension.scripts.OutputPanel  - groovy.lang.MissingMethodException: No signature of method: org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.getRequiredParamsNames() is applicable for argument types: () values: []
java.lang.RuntimeException: groovy.lang.MissingMethodException: No signature of method: org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.getRequiredParamsNames() is applicable for argument types: () values: []
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.invokeImplSafe(GroovyScriptEngineImpl.java:383)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.lambda$makeInterface$0(GroovyScriptEngineImpl.java:429)
	at com.sun.proxy.$Proxy11.getRequiredParamsNames(Unknown Source)
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.processors.FuzzerHttpMessageScriptProcessorAdapter.validateRequiredParameters(FuzzerHttpMessageScriptProcessorAdapter.java:148)
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.processors.FuzzerHttpMessageScriptProcessorAdapter.initialise(FuzzerHttpMessageScriptProcessorAdapter.java:132)
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.processors.FuzzerHttpMessageScriptProcessorAdapter.initialiseIfNotInitialised(FuzzerHttpMessageScriptProcessorAdapter.java:111)
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.processors.FuzzerHttpMessageScriptProcessorAdapter.processMessage(FuzzerHttpMessageScriptProcessorAdapter.java:84)
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.HttpFuzzer.preProcessMessage(HttpFuzzer.java:197)
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.HttpFuzzerTask.runImpl(HttpFuzzerTask.java:49)
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.HttpFuzzerTask.runImpl(HttpFuzzerTask.java:30)
	at org.zaproxy.zap.extension.fuzz.AbstractFuzzerTask.run(AbstractFuzzerTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: groovy.lang.MissingMethodException: No signature of method: org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.getRequiredParamsNames() is applicable for argument types: () values: []
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.callGlobal(GroovyScriptEngineImpl.java:404)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.callGlobal(GroovyScriptEngineImpl.java:389)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.invokeImplSafe(GroovyScriptEngineImpl.java:380)
	... 13 more
339922 [ZAP-FuzzerThreadPool-0-thread-1] WARN org.zaproxy.zap.extension.fuzz.httpfuzzer.HttpFuzzer  - Error while executing a processor, it will not be called again:
org.zaproxy.zap.extension.fuzz.httpfuzzer.ProcessingException: Failed to process the payload:
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.processors.FuzzerHttpMessageScriptProcessorAdapter.handleScriptException(FuzzerHttpMessageScriptProcessorAdapter.java:164)
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.processors.FuzzerHttpMessageScriptProcessorAdapter.initialise(FuzzerHttpMessageScriptProcessorAdapter.java:141)
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.processors.FuzzerHttpMessageScriptProcessorAdapter.initialiseIfNotInitialised(FuzzerHttpMessageScriptProcessorAdapter.java:111)
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.processors.FuzzerHttpMessageScriptProcessorAdapter.processMessage(FuzzerHttpMessageScriptProcessorAdapter.java:84)
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.HttpFuzzer.preProcessMessage(HttpFuzzer.java:197)
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.HttpFuzzerTask.runImpl(HttpFuzzerTask.java:49)
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.HttpFuzzerTask.runImpl(HttpFuzzerTask.java:30)
	at org.zaproxy.zap.extension.fuzz.AbstractFuzzerTask.run(AbstractFuzzerTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: groovy.lang.MissingMethodException: No signature of method: org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.getRequiredParamsNames() is applicable for argument types: () values: []
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.invokeImplSafe(GroovyScriptEngineImpl.java:383)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.lambda$makeInterface$0(GroovyScriptEngineImpl.java:429)
	at com.sun.proxy.$Proxy11.getRequiredParamsNames(Unknown Source)
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.processors.FuzzerHttpMessageScriptProcessorAdapter.validateRequiredParameters(FuzzerHttpMessageScriptProcessorAdapter.java:148)
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.processors.FuzzerHttpMessageScriptProcessorAdapter.initialise(FuzzerHttpMessageScriptProcessorAdapter.java:132)
	... 9 more
Caused by: groovy.lang.MissingMethodException: No signature of method: org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.getRequiredParamsNames() is applicable for argument types: () values: []
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.callGlobal(GroovyScriptEngineImpl.java:404)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.callGlobal(GroovyScriptEngineImpl.java:389)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.invokeImplSafe(GroovyScriptEngineImpl.java:380)
	... 13 more
```

**Comment by thc202** [comment]
Thanks for the details, the current changes do not address the underlying issue though, could you apply the following changes?
```diff
--- a/addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/FuzzerHttpMessageScriptProcessorAdapter.java
+++ b/addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/FuzzerHttpMessageScriptProcessorAdapter.java
@@ -21,7 +21,6 @@ package org.zaproxy.zap.extension.fuzz.httpfuzzer.processors;
 
 import java.util.Collections;
 import java.util.Map;
-import org.parosproxy.paros.Constant;
 import org.parosproxy.paros.control.Control;
 import org.parosproxy.paros.network.HttpMessage;
 import org.zaproxy.zap.extension.fuzz.httpfuzzer.HttpFuzzResult;
@@ -125,22 +124,11 @@ public class FuzzerHttpMessageScriptProcessorAdapter implements HttpFuzzerMessag
                 Control.getSingleton().getExtensionLoader().getExtension(ExtensionScript.class);
         if (extensionScript != null) {
             try {
-                scriptProcessor =
-                        extensionScript.getInterface(
-                                scriptWrapper, HttpFuzzerProcessorScript.class);
-                if (scriptProcessor != null) {
-                    validateRequiredParameters();
-                } else {
-                    extensionScript.handleFailedScriptInterface(
-                            scriptWrapper,
-                            Constant.messages.getString(
-                                    "fuzz.httpfuzzer.processor.scriptProcessor.warnNoInterface.message",
-                                    scriptWrapper.getName()));
-                }
+                scriptProcessor = HttpFuzzerProcessorScriptProxy.create(scriptWrapper);
             } catch (Exception e) {
-                handleScriptException(e);
                 throw new ProcessingException("Failed to instantiate the script processor:", e);
             }
+            validateRequiredParameters();
         }
     }
``` 
Also , tweak the changelog to mention instead that the optional functions are now properly handled.

**Comment by t4skforce** [comment]
Done, thanks for actually fixing the underlying issue @thc202 I still like to keep the methods in the template for groovy as it is a nice reference if you need them. Also the js template includes them for reference.

**Comment by thc202** [comment]
Agreed, I wasn't suggesting changing the template. I didn't notice the first changelog changed was for the Groovy add-on...

**Comment by thc202** [comment]
Thanks!

**Pull request merged**
