### PR TITLE
ascanrulesBeta: More example alerts

### PR DESCRIPTION
**Pull request by kingthorin**
## Overview
- CHANGELOG > Add notes.
- Scan rules > Add example alert functionality (6119).
- Unit tests > Assert the new example alerts.

## Related Issues
- zaproxy/zaproxy#6119

## Checklist
- [na] Update help
- [x] Update changelog
- [x] Run `./gradlew spotlessApply` for code formatting
- [x] Write tests
- [x] Check code coverage
- [x] Sign-off commits
- [x] Squash commits
- [x] Use a descriptive title

### CODE REVIEW

**Comment by thc202** [comment]
The build is failing.

**Comment by thc202** [comment]
How were the tests fixed?

There's a typo in the add-on ID.

**Comment by kingthorin** [comment]
I fixed the expected string. I had assumed the cookie collection was processed in order but apparently it's processed backwards 🤷‍♂️

**Comment by thc202** [comment]
The push does not have any changes(?). The set used does not have a reliable ordering.

**Comment by kingthorin** [comment]
Oh I didn't realize I'd just been lucky. I had done multiple runs locally but not any statistically significant number.

Shall I switch specifically to a SortedSet for the example? Or use string starts with for the test?

**Comment by thc202** [comment]
Better with `SortedSet`, we do need a predictable/constant ordering otherwise we'll have unwanted changes in the website.

**Comment by kingthorin** [comment]
Done

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Review by psiinon — APPROVED** [review]

**Pull request merged**
