### PR TITLE
ascanrules: Update reference links (http -> https) Alert: 90020

### PR DESCRIPTION
**Pull request by 8linkz**
## Overview
I have only replaced http with https, the actual link has remained the same.
https://www.zaproxy.org/docs/alerts/90020/

## Related Issues
Related to: https://github.com/zaproxy/zaproxy/issues/8262

## Checklist
- [ ] Update help
- [x] Update changelog
- [ ] Run `./gradlew spotlessApply` for code formatting
- [ ] Write tests
- [ ] Check code coverage
- [x] Sign-off commits
- [ ] Squash commits
- [ ] Use a descriptive title

For more details, please refer to the [developer rules and guidelines](https://www.zaproxy.org/docs/developer/dev-rules-and-guidelines/).

### CODE REVIEW

**Comment by 8linkz** [comment]
> This scan rule is being updated by #5181.

https://github.com/zaproxy/zaproxy/issues/8262 -> then please leave it here - was still "open"

**Comment by thc202** [comment]
Ideally one should ask/tell first in the issue what tasks they want to work on (that goes for everyone wink wink @kingthorin).

**Comment by 8linkz** [comment]
So in short, the PR here can be closed because it's a duplicate?

**Comment by kingthorin** [comment]
I believe so. I did a bunch of updates to the issue(s), hopefully that helps others/future work.

**Comment by 8linkz** [comment]
dublicate

**Pull request closed without merging**
