### PR TITLE
webdrivers: Prepare next dev iteration

### PR DESCRIPTION
**Pull request by kingthorin**
Update version and changelog

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
Build failure seems unrelated, restarted.

**Comment by kingthorin** [comment]
The Java 11 build keeps failing with an ascanrulesAlpha test issue:
```console
> Task :addOns:ascanrulesAlpha:test FAILED
2708> Task :addOns:ascanrules:spotlessJava
2709
2710FAILURE: Build failed with an exception.
2711
2712* What went wrong:
2713Execution failed for task ':addOns:ascanrulesAlpha:test'.
2714> failed to scan jar file for packages (/home/travis/.gradle/caches/modules-2/files-2.1/com.io7m.xom/xom/1.2.10/4165e25bef19aad134f6498cc277110b9bc5e52b/xom-1.2.10.jar)
```

**Comment by kingthorin** [comment]
Finally passed

**Comment by thc202** [comment]
It was a problem with the cache.

**Comment by kingthorin** [comment]
Thanks

**Pull request merged**
