### PR TITLE
requester: improve reporting of TLS errors

### PR DESCRIPTION
**Pull request by thc202**
Handle `SSLException` separately to report a better error, migration of
core change zaproxy/zaproxy#3204.

### CODE REVIEW

**Comment by thc202** [comment]
Need to tweak the changelog.

**Review by ricekot — APPROVED** [review]
Thanks!

**Comment by kingthorin** [comment]
Do the Messages.properties entries already exist?

**Comment by thc202** [comment]
Yes, they are in the Network add-on.

**Review by kingthorin — APPROVED** [review]

**Pull request merged**
