### PR TITLE
Add .env File Scanner

### PR DESCRIPTION
**Pull request by kingthorin**
EnvFileScanner.java - Add a new Active Scanner to check for .env files.
ascanalpha.html - Added relevant help entry.
Messages.properties - Added i18n strings.
ZapAddOn.xml - Updated changes section.

See: https://mobile.twitter.com/svblxyz/status/1045013939904532482

### CODE REVIEW

**Comment by kingthorin** [comment]
Manifest tweaked

**Comment by thc202** [comment]
Thanks!

**Comment by thc202** [comment]
Any other changes or good to release?

**Comment by kingthorin** [comment]
Good to release as far as I know.

**Pull request merged**
